// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ClientAdapterDB is an autogenerated mock type for the ClientAdapterDB type
type ClientAdapterDB struct {
	mock.Mock
}

type ClientAdapterDB_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientAdapterDB) EXPECT() *ClientAdapterDB_Expecter {
	return &ClientAdapterDB_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: key
func (_m *ClientAdapterDB) Get(key []byte) ([]byte, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientAdapterDB_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ClientAdapterDB_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key []byte
func (_e *ClientAdapterDB_Expecter) Get(key interface{}) *ClientAdapterDB_Get_Call {
	return &ClientAdapterDB_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *ClientAdapterDB_Get_Call) Run(run func(key []byte)) *ClientAdapterDB_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *ClientAdapterDB_Get_Call) Return(value []byte, err error) *ClientAdapterDB_Get_Call {
	_c.Call.Return(value, err)
	return _c
}

func (_c *ClientAdapterDB_Get_Call) RunAndReturn(run func([]byte) ([]byte, error)) *ClientAdapterDB_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Has provides a mock function with given fields: key
func (_m *ClientAdapterDB) Has(key []byte) (bool, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Has")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (bool, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func([]byte) bool); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientAdapterDB_Has_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Has'
type ClientAdapterDB_Has_Call struct {
	*mock.Call
}

// Has is a helper method to define mock.On call
//   - key []byte
func (_e *ClientAdapterDB_Expecter) Has(key interface{}) *ClientAdapterDB_Has_Call {
	return &ClientAdapterDB_Has_Call{Call: _e.mock.On("Has", key)}
}

func (_c *ClientAdapterDB_Has_Call) Run(run func(key []byte)) *ClientAdapterDB_Has_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *ClientAdapterDB_Has_Call) Return(has bool, err error) *ClientAdapterDB_Has_Call {
	_c.Call.Return(has, err)
	return _c
}

func (_c *ClientAdapterDB_Has_Call) RunAndReturn(run func([]byte) (bool, error)) *ClientAdapterDB_Has_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientAdapterDB creates a new instance of ClientAdapterDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientAdapterDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientAdapterDB {
	mock := &ClientAdapterDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
