[relaychain]
chain_spec_path = "chain/westend-local/westend-local-spec-raw.json"

chain = "westend-local"

[[relaychain.nodes]]
name = "alice"
command = "gossamer"
validator = true
args = ["--key alice"]

[[relaychain.nodes]]
name = "bob"
command = "gossamer"
validator = true
args = ["--key bob"]

[[relaychain.nodes]]
name = "charlie"
command = "gossamer"
validator = true
args = ["--key charlie"]
