[relaychain]
#default_image = "docker.io/parity/polkadot:latest"
#default_command = "polkadot"
#default_args = [ "-lparachain=debug" ]
chain_spec_path = "chain/westend-local/westend-local-spec-raw.json"
chain = "westend-local"

  [[relaychain.nodes]]
  name = "alice"
  command = "polkadot"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  command = "gossamer"
  args = ["--key bob"]

#  [[relaychain.nodes]]
#  name = "charlie"
#  command = "polkadot"
#  validator = true

[[parachains]]
id = 100

  [parachains.collator]
  name = "collator01"
  image = "docker.io/parity/polkadot-parachain:latest"
  command = "polkadot-parachain"
  args = ["-lparachain=debug"]