package parachain

import (
	"testing"

	"github.com/ChainSafe/gossamer/lib/common"
	"github.com/stretchr/testify/require"
)

func TestEncodeStatementFetchingRequest(t *testing.T) {
	t.Parallel()

	testCases := []struct {
		name           string
		request        StatementFetchingRequest
		expectedEncode []byte
	}{
		{
			// expected encoding is generated by running rust test code:
			// fn statement_request() {
			// 	let hash4 = Hash::repeat_byte(4);
			// 	let statement_fetching_request = StatementFetchingRequest{
			// 		relay_parent: hash4,
			// 		candidate_hash: CandidateHash(hash4)
			// 	};
			// 	println!(
			// 		"statement_fetching_request encode => {:?}\n\n",
			// 		statement_fetching_request.encode()
			// 	);
			// }
			name: "all 4 in common.Hash",
			request: StatementFetchingRequest{
				RelayParent:   getDummyHash(4),
				CandidateHash: CandidateHash{Value: getDummyHash(4)},
			},
			expectedEncode: common.MustHexToBytes(testDataStatement["all4InCommonHash"]),
		},
		{
			name: "all 7 in common.Hash",
			request: StatementFetchingRequest{
				RelayParent:   getDummyHash(7),
				CandidateHash: CandidateHash{Value: getDummyHash(7)},
			},
			expectedEncode: common.MustHexToBytes(testDataStatement["all7InCommonHash"]),
		},
	}

	for _, c := range testCases {
		c := c
		t.Run(c.name, func(t *testing.T) {
			t.Parallel()
			actualEncode, err := c.request.Encode()
			require.NoError(t, err)
			require.Equal(t, c.expectedEncode, actualEncode)
		})
	}
}

func TestStatementFetchingResponse(t *testing.T) {
	t.Parallel()

	hash5 := getDummyHash(5)

	var collatorID CollatorID
	tempCollatID := common.MustHexToBytes("0x48215b9d322601e5b1a95164cea0dc4626f545f98343d07f1551eb9543c4b147")
	copy(collatorID[:], tempCollatID)

	var collatorSignature CollatorSignature
	tempSignature := common.MustHexToBytes(testDataStatement["collatorSignature"])
	copy(collatorSignature[:], tempSignature)

	missingDataInStatement := MissingDataInStatement{
		Descriptor: CandidateDescriptor{
			ParaID:                      uint32(1),
			RelayParent:                 hash5,
			Collator:                    collatorID,
			PersistedValidationDataHash: hash5,
			PovHash:                     hash5,
			ErasureRoot:                 hash5,
			Signature:                   collatorSignature,
			ParaHead:                    hash5,
			ValidationCodeHash:          ValidationCodeHash(hash5),
		},
		Commitments: CandidateCommitments{
			UpwardMessages:            []UpwardMessage{{1, 2, 3}},
			NewValidationCode:         &ValidationCode{1, 2, 3},
			HeadData:                  headData{1, 2, 3},
			ProcessedDownwardMessages: uint32(5),
			HrmpWatermark:             uint32(0),
		},
	}

	EncodedValue := common.MustHexToBytes(testDataStatement["hexOfStatementFetchingResponse"])

	response := NewStatementFetchingResponse()
	err := response.Set(missingDataInStatement)
	require.NoError(t, err)

	t.Run("Encode StatementFetchingResponse", func(t *testing.T) {
		t.Parallel()

		actualEncode, err := response.Encode()
		require.NoError(t, err)

		require.Equal(t, EncodedValue, actualEncode)
	})

	t.Run("Decode StatementFetchingResponse", func(t *testing.T) {
		t.Parallel()
		err := response.Decode(EncodedValue)
		require.NoError(t, err)

		actualData, err := response.Value()
		require.NoError(t, err)

		require.EqualValues(t, missingDataInStatement, actualData)
	})
}
