// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FinalityGadget is an autogenerated mock type for the FinalityGadget type
type FinalityGadget struct {
	mock.Mock
}

// VerifyBlockJustification provides a mock function with given fields: _a0
func (_m *FinalityGadget) VerifyBlockJustification(_a0 []byte) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
