// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	types "github.com/ChainSafe/gossamer/dot/types"
)

// TransactionState is an autogenerated mock type for the TransactionState type
type TransactionState struct {
	mock.Mock
}

// RemoveExtrinsic provides a mock function with given fields: ext
func (_m *TransactionState) RemoveExtrinsic(ext types.Extrinsic) {
	_m.Called(ext)
}
