# See https://golangci-lint.run/usage/configuration/#config-file

run:
  deadline: 10m

  build-tags:
    - integration

  skip-files:
    - .*mock_.*\.go
    - .*mocks\/.*\.go

linters-settings:
  govet:
    # report about shadowed variables
    check-shadowing: true

  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/davecgh/go-spew/spew

  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 120
    # tab width in spaces. Default to 1.
    tab-width: 1

  misspell:
    locale: UK
    ignore-words:
      - gossamer
      - flavor
      - finalized
      - finalize
      - initialize

linters:
  enable:
    - bodyclose
    - depguard
    - errcheck
    - exportloopref
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nilerr
    - nilnil
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - varcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - ineffassign

    - text: "exported: exported var Err*"
      linters:
        - revive

    - text: "exported: exported method [a-zA-Z]*.MarshalJSON should have comment or be unexported"
      linters:
        - revive

    - text: 'shadow: declaration of "err" shadows declaration*'
      linters:
        - govet

    - text: 'shadow: declaration of "ok" shadows declaration*'
      linters:
        - govet

    - linters:
        - revive
      text: "package comment should be of the form"

    - linters:
        - revive
      path: lib/runtime/life/
      text: "don't use underscores in Go names;"

    - linters:
        - nolintlint
      source: "^//nolint:revive"

    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "

    - source: "// https://"
      linters:
        - lll

    - source: "// See https://"
      linters:
        - lll

    - text: "G204: Subprocess launched with variable"
      linters:
        - gosec

  exclude-use-default: false
