# See https://golangci-lint.run/usage/configuration/#config-file

run:
  deadline: 10m

  build-tags:
    - integration

  skip-files:
    - .*mock_.*\.go
    - .*mocks\/.*\.go

linters-settings:
  govet:
    # report about shadowed variables
    check-shadowing: true

  revive:
    severity: warning
    confidence: 0.8

  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 120
    # tab width in spaces. Default to 1.
    tab-width: 1
  
  nilnil:
    checked-types:
      - func
      - iface
      - map
      - chan

  misspell:
    locale: UK
    ignore-words:
      - gossamer
      - flavor
      - finalized
      - finalize
      - initialize

linters:
  enable:
    - bodyclose
    - errcheck
    - exportloopref
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nilerr
    - nilnil
    - nolintlint
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - ineffassign

    - text: "exported: exported var Err*"
      linters:
        - revive

    - text: "exported: exported method [a-zA-Z]*.MarshalJSON should have comment or be unexported"
      linters:
        - revive

    - text: 'shadow: declaration of "err" shadows declaration*'
      linters:
        - govet

    - text: 'shadow: declaration of "ok" shadows declaration*'
      linters:
        - govet

    - linters:
        - revive
      text: "package comment should be of the form"

    - linters:
        - nolintlint
      source: "^//nolint:revive"

    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "

    - linters:
        - lll
      path: lib/runtime/wasmer/imports\.go
      source: "^// extern "

    - linters:
        - lll
      path: lib/runtime/wasmer/imports\.go
      source: '{"ext_.+", ext_.+, C.ext_.+},$'

    - source: "// https://"
      linters:
        - lll

    - source: "// See https://"
      linters:
        - lll

    - text: "G204: Subprocess launched with variable"
      linters:
        - gosec

  exclude-use-default: false
