language: go

go:
- 1.11

before_script:
- wget -O - -q https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.15.0
- go get -v -t -d ./...
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
script:
- go test -v -coverprofile c.out ./... && ./cc-test-reporter after-build --exit-code $?
- gofmt -d ./..
- ./bin/golangci-lint run
