coverage:
  range: "60...80"

ignore:
  - "docs/**/*"
  - "tests/**/*"
  - "scripts/**/*"
  - "cmd/gossamer/test_inputs/*"
  - "chain/**/*"
  - "dot/config/**/*"
  - "dot/rpc/modules/test_data"
  - "lib/runtime/test_data"
  - "**/errors.go"
  - "**/*/errors.go"
  - "**/*/mocks/*.go"
  - "**/*/mock_*.go"
  - "go.mod"
  - "go.sum"
