FROM golang:1.23

ARG chain="polkadot"
ARG basepath="~/.local/share/gossamer"

ENV chain=${chain}
ENV GSSMRHOME=${basepath}

WORKDIR /gossamer

COPY . .

ARG GO_BUILD_FLAGS
RUN go build \
    -trimpath \
    -o /gossamer/bin/gossamer \
    ${GO_BUILD_FLAGS} \
    ./cmd/gossamer

EXPOSE 7001 8545 8546 8540 9876 6060
ENTRYPOINT [ "/gossamer/bin/gossamer" ]
