// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ChainSafe/gossamer/dot/parachain/backing (interfaces: Table,ImplicitView)
//
// Generated by this command:
//
//	mockgen -destination=mocks_test.go -package=backing . Table,ImplicitView
//

// Package backing is a generated GoMock package.
package backing

import (
	reflect "reflect"

	parachaintypes "github.com/ChainSafe/gossamer/dot/parachain/types"
	common "github.com/ChainSafe/gossamer/lib/common"
	gomock "go.uber.org/mock/gomock"
)

// MockTable is a mock of Table interface.
type MockTable struct {
	ctrl     *gomock.Controller
	recorder *MockTableMockRecorder
	isgomock struct{}
}

// MockTableMockRecorder is the mock recorder for MockTable.
type MockTableMockRecorder struct {
	mock *MockTable
}

// NewMockTable creates a new mock instance.
func NewMockTable(ctrl *gomock.Controller) *MockTable {
	mock := &MockTable{ctrl: ctrl}
	mock.recorder = &MockTableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTable) EXPECT() *MockTableMockRecorder {
	return m.recorder
}

// attestedCandidate mocks base method.
func (m *MockTable) attestedCandidate(arg0 parachaintypes.CandidateHash, arg1 *tableContext, arg2 uint32) (*attestedCandidate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "attestedCandidate", arg0, arg1, arg2)
	ret0, _ := ret[0].(*attestedCandidate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// attestedCandidate indicates an expected call of attestedCandidate.
func (mr *MockTableMockRecorder) attestedCandidate(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "attestedCandidate", reflect.TypeOf((*MockTable)(nil).attestedCandidate), arg0, arg1, arg2)
}

// drainMisbehaviors mocks base method.
func (m *MockTable) drainMisbehaviors() map[parachaintypes.ValidatorIndex][]parachaintypes.Misbehaviour {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "drainMisbehaviors")
	ret0, _ := ret[0].(map[parachaintypes.ValidatorIndex][]parachaintypes.Misbehaviour)
	return ret0
}

// drainMisbehaviors indicates an expected call of drainMisbehaviors.
func (mr *MockTableMockRecorder) drainMisbehaviors() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "drainMisbehaviors", reflect.TypeOf((*MockTable)(nil).drainMisbehaviors))
}

// getCommittedCandidateReceipt mocks base method.
func (m *MockTable) getCommittedCandidateReceipt(arg0 parachaintypes.CandidateHash) (parachaintypes.CommittedCandidateReceiptV2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getCommittedCandidateReceipt", arg0)
	ret0, _ := ret[0].(parachaintypes.CommittedCandidateReceiptV2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getCommittedCandidateReceipt indicates an expected call of getCommittedCandidateReceipt.
func (mr *MockTableMockRecorder) getCommittedCandidateReceipt(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getCommittedCandidateReceipt", reflect.TypeOf((*MockTable)(nil).getCommittedCandidateReceipt), arg0)
}

// importStatement mocks base method.
func (m *MockTable) importStatement(arg0 *tableContext, arg1 parachaintypes.GroupIndex, arg2 parachaintypes.SignedFullStatement) (*Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "importStatement", arg0, arg1, arg2)
	ret0, _ := ret[0].(*Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// importStatement indicates an expected call of importStatement.
func (mr *MockTableMockRecorder) importStatement(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "importStatement", reflect.TypeOf((*MockTable)(nil).importStatement), arg0, arg1, arg2)
}

// MockImplicitView is a mock of ImplicitView interface.
type MockImplicitView struct {
	ctrl     *gomock.Controller
	recorder *MockImplicitViewMockRecorder
	isgomock struct{}
}

// MockImplicitViewMockRecorder is the mock recorder for MockImplicitView.
type MockImplicitViewMockRecorder struct {
	mock *MockImplicitView
}

// NewMockImplicitView creates a new mock instance.
func NewMockImplicitView(ctrl *gomock.Controller) *MockImplicitView {
	mock := &MockImplicitView{ctrl: ctrl}
	mock.recorder = &MockImplicitViewMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImplicitView) EXPECT() *MockImplicitViewMockRecorder {
	return m.recorder
}

// ActivateLeaf mocks base method.
func (m *MockImplicitView) ActivateLeaf(leafHash common.Hash) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateLeaf", leafHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateLeaf indicates an expected call of ActivateLeaf.
func (mr *MockImplicitViewMockRecorder) ActivateLeaf(leafHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateLeaf", reflect.TypeOf((*MockImplicitView)(nil).ActivateLeaf), leafHash)
}

// AllAllowedRelayParents mocks base method.
func (m *MockImplicitView) AllAllowedRelayParents() []common.Hash {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllAllowedRelayParents")
	ret0, _ := ret[0].([]common.Hash)
	return ret0
}

// AllAllowedRelayParents indicates an expected call of AllAllowedRelayParents.
func (mr *MockImplicitViewMockRecorder) AllAllowedRelayParents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllAllowedRelayParents", reflect.TypeOf((*MockImplicitView)(nil).AllAllowedRelayParents))
}

// KnownAllowedRelayParentsUnder mocks base method.
func (m *MockImplicitView) KnownAllowedRelayParentsUnder(blockHash common.Hash, paraID *parachaintypes.ParaID) []common.Hash {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KnownAllowedRelayParentsUnder", blockHash, paraID)
	ret0, _ := ret[0].([]common.Hash)
	return ret0
}

// KnownAllowedRelayParentsUnder indicates an expected call of KnownAllowedRelayParentsUnder.
func (mr *MockImplicitViewMockRecorder) KnownAllowedRelayParentsUnder(blockHash, paraID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KnownAllowedRelayParentsUnder", reflect.TypeOf((*MockImplicitView)(nil).KnownAllowedRelayParentsUnder), blockHash, paraID)
}

// Leaves mocks base method.
func (m *MockImplicitView) Leaves() []common.Hash {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Leaves")
	ret0, _ := ret[0].([]common.Hash)
	return ret0
}

// Leaves indicates an expected call of Leaves.
func (mr *MockImplicitViewMockRecorder) Leaves() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Leaves", reflect.TypeOf((*MockImplicitView)(nil).Leaves))
}

// deactivateLeaf mocks base method.
func (m *MockImplicitView) deactivateLeaf(leafHash common.Hash) []common.Hash {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "deactivateLeaf", leafHash)
	ret0, _ := ret[0].([]common.Hash)
	return ret0
}

// deactivateLeaf indicates an expected call of deactivateLeaf.
func (mr *MockImplicitViewMockRecorder) deactivateLeaf(leafHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "deactivateLeaf", reflect.TypeOf((*MockImplicitView)(nil).deactivateLeaf), leafHash)
}
