// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ChainSafe/gossamer/dot/network (interfaces: WarpSyncProvider)
//
// Generated by this command:
//
//	mockgen -destination=mock_warp_sync_provider_test.go -package network . WarpSyncProvider
//

// Package network is a generated GoMock package.
package network

import (
	reflect "reflect"

	grandpa "github.com/ChainSafe/gossamer/internal/primitives/consensus/grandpa"
	common "github.com/ChainSafe/gossamer/lib/common"
	warpsync "github.com/ChainSafe/gossamer/lib/grandpa/warpsync"
	gomock "go.uber.org/mock/gomock"
)

// MockWarpSyncProvider is a mock of WarpSyncProvider interface.
type MockWarpSyncProvider struct {
	ctrl     *gomock.Controller
	recorder *MockWarpSyncProviderMockRecorder
	isgomock struct{}
}

// MockWarpSyncProviderMockRecorder is the mock recorder for MockWarpSyncProvider.
type MockWarpSyncProviderMockRecorder struct {
	mock *MockWarpSyncProvider
}

// NewMockWarpSyncProvider creates a new mock instance.
func NewMockWarpSyncProvider(ctrl *gomock.Controller) *MockWarpSyncProvider {
	mock := &MockWarpSyncProvider{ctrl: ctrl}
	mock.recorder = &MockWarpSyncProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWarpSyncProvider) EXPECT() *MockWarpSyncProviderMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockWarpSyncProvider) Generate(start common.Hash) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", start)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockWarpSyncProviderMockRecorder) Generate(start any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockWarpSyncProvider)(nil).Generate), start)
}

// Verify mocks base method.
func (m *MockWarpSyncProvider) Verify(encodedProof []byte, setId grandpa.SetID, authorities grandpa.AuthorityList) (*warpsync.WarpSyncVerificationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", encodedProof, setId, authorities)
	ret0, _ := ret[0].(*warpsync.WarpSyncVerificationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockWarpSyncProviderMockRecorder) Verify(encodedProof, setId, authorities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockWarpSyncProvider)(nil).Verify), encodedProof, setId, authorities)
}
