// Copyright 2024 ChainSafe Systems (ON)
// SPDX-License-Identifier: LGPL-3.0-only

package statemachine

import "github.com/ChainSafe/gossamer/internal/primitives/core/offchain"

// OffchainChangesCollection is slice of storage values.
type OffchainChangesCollection []struct {
	PrefixKey struct {
		Prefix []byte
		Key    []byte
	}
	ValueOperation offchain.OffchainOverlayedChange
}

// IndexOperations is interface constraint of [IndexOperation].
type IndexOperations interface {
	IndexOperationInsert | IndexOperationRenew
}

// IndexOperation is a transaction index operation.
type IndexOperation interface {
	isIndexOperation()
}

// IndexOperationInsert is an insert transaction into index.
type IndexOperationInsert struct {
	// Extrinsic index in the current block.
	Extrinsic uint32
	// Data content hash.
	Hash []byte
	// Indexed data size.
	Size uint32
}

// IndexOperationRenew renews existing transaction storage.
type IndexOperationRenew struct {
	// Extrinsic index in the current block.
	Extrinsic uint32
	// Referenced index hash.
	Hash []byte
}

func (IndexOperationInsert) isIndexOperation() {}
func (IndexOperationRenew) isIndexOperation()  {}

// / A storage changes structure that can be generated by the data collected in [`OverlayedChanges`].
// /
// / This contains all the changes to the storage and transactions to apply theses changes to the
// / backend.
// pub struct StorageChanges<Transaction, H: Hasher> {
type StorageChanges[Transaction, H any] struct {
	/// All changes to the main storage.
	///
	/// A value of `None` means that it was deleted.
	// pub main_storage_changes: StorageCollection,
	MainStorageChanges StorageCollection
	/// All changes to the child storages.
	// pub child_storage_changes: ChildStorageCollection,
	ChildStorageChanges ChildStorageCollection
	/// Offchain state changes to write to the offchain database.
	// pub offchain_storage_changes: OffchainChangesCollection,
	OffchainStorageChanges OffchainChangesCollection
	/// A transaction for the backend that contains all changes from
	/// [`main_storage_changes`](StorageChanges::main_storage_changes) and from
	/// [`child_storage_changes`](StorageChanges::child_storage_changes).
	/// [`offchain_storage_changes`](StorageChanges::offchain_storage_changes).
	// pub transaction: Transaction,
	Transaction Transaction
	/// The storage root after applying the transaction.
	// pub transaction_storage_root: H::Out,
	TransactionStorageRoot H
	/// Changes to the transaction index,
	// pub transaction_index_changes: Vec<IndexOperation>,
	TransactionIndexChanges []IndexOperation
}
