package parachaintypes

import (
	"encoding/binary"
	"fmt"

	"github.com/ChainSafe/gossamer/lib/common"
	"github.com/ChainSafe/gossamer/pkg/scale"
)

// CandidateDescriptorV2 is a descriptor for a parachain candidate.
type CandidateDescriptorV2 struct {
	// The ID of the para this is a candidate for.
	ParaID ParaID
	// RelayParent is the hash of the relay-chain block this should be executed in
	// the context of.
	RelayParent common.Hash
	// Version field. The raw value here is not exposed, instead it is used
	// to determine the `CandidateDescriptorVersion`, see `fn version()`.
	// For the current version this field is set to `0` and will be incremented
	// by next versions.
	Version uint8
	// The core index where the candidate is backed.
	CoreIndex uint16
	// The session index of the candidate relay parent.
	SessionIndex SessionIndex
	// Reserved bytes.
	Reserved1 [25]uint8
	// PersistedValidationDataHash is the blake2-256 hash of the persisted validation data. This is extra data derived from
	// relay-chain state which may vary based on bitfields included before the candidate.
	// Thus, it cannot be derived entirely from the relay-parent.
	PersistedValidationDataHash common.Hash
	// PovHash is the hash of the `pov-block`.
	PovHash common.Hash
	// ErasureRoot is the root of a block's erasure encoding Merkle tree.
	ErasureRoot common.Hash
	// Reserved bytes.
	Reserved2 [64]uint8
	// ParaHead is the hash of the para header that is being generated by this candidate.
	ParaHead common.Hash
	// ValidationCodeHash is the blake2-256 hash of the validation code bytes.
	ValidationCodeHash ValidationCodeHash
}

// CommittedCandidateReceiptV2 is a candidate-receipt with commitments directly included.
type CommittedCandidateReceiptV2 struct {
	// The descriptor of the candidate.
	Descriptor CandidateDescriptorV2 `scale:"1"`
	// The commitments of the candidate receipt.
	Commitments CandidateCommitments `scale:"2"`
}

// ToPlain converts a CommittedCandidateReceiptV2 to a CandidateReceiptV2
func (ccr CommittedCandidateReceiptV2) ToPlain() CandidateReceiptV2 {
	return CandidateReceiptV2{
		Descriptor:      ccr.Descriptor,
		CommitmentsHash: ccr.Commitments.Hash(),
	}
}

// Hash returns the hash of the CommittedCandidateReceiptV2
func (ccr CommittedCandidateReceiptV2) Hash() (common.Hash, error) {
	return ccr.ToPlain().Hash()
}

func (ccrV1 CommittedCandidateReceipt) V2() CommittedCandidateReceiptV2 {
	return CommittedCandidateReceiptV2{
		Descriptor:  ccrV1.Descriptor.V2(),
		Commitments: ccrV1.Commitments,
	}
}

// CandidateReceiptV2 A receipt for a parachain candidate.
type CandidateReceiptV2 struct {
	// The candidate descriptor
	Descriptor CandidateDescriptorV2 `scale:"1"`
	// The candidate event.
	CommitmentsHash common.Hash `scale:"2"`
}

func (cr CandidateReceiptV2) Hash() (common.Hash, error) {
	bytes, err := scale.Marshal(cr)
	if err != nil {
		return common.Hash{}, fmt.Errorf("marshalling CommittedCandidateReceipt: %w", err)
	}

	return common.Blake2bHash(bytes)
}

// V2 converts a CandidateReceipt to a CandidateReceiptV2
func (crV1 CandidateReceipt) V2() CandidateReceiptV2 {
	crV2 := CandidateReceiptV2{
		Descriptor:      crV1.Descriptor.V2(),
		CommitmentsHash: crV1.CommitmentsHash,
	}

	return crV2
}

// V2 converts a CandidateDescriptor to a CandidateDescriptorV2
func (cdV1 CandidateDescriptor) V2() CandidateDescriptorV2 {
	// use first byte of collator as version
	version := cdV1.Collator[0]
	// next two bytes of collator are core index
	coreIndex := bytesToUint16(cdV1.Collator[1:3])
	// next four bytes of collator are session index
	sessionIndex := SessionIndex(bytesToUint16(cdV1.Collator[3:7]))
	// use remaining 25 bytes as reserved1
	var reserved1 [25]byte
	copy(reserved1[:], cdV1.Collator[7:])

	// use collator signature as reserved2
	var reserved2 [64]byte = cdV1.Signature

	return CandidateDescriptorV2{
		ParaID:                      cdV1.ParaID,
		RelayParent:                 cdV1.RelayParent,
		Version:                     version,
		CoreIndex:                   coreIndex,
		SessionIndex:                sessionIndex,
		Reserved1:                   reserved1,
		PersistedValidationDataHash: cdV1.PersistedValidationDataHash,
		PovHash:                     cdV1.PovHash,
		ErasureRoot:                 cdV1.ErasureRoot,
		Reserved2:                   reserved2,
		ParaHead:                    cdV1.ParaHead,
		ValidationCodeHash:          cdV1.ValidationCodeHash,
	}
}

// bytesToUint16 converts a byte slice to a uint16 using the native endianness
func bytesToUint16(bytes []byte) uint16 {
	// Binary.BigEndian or Binary.LittleEndian depending on platform
	return binary.NativeEndian.Uint16(bytes)
}
