package parachaintypes

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"

	"github.com/ChainSafe/gossamer/lib/common"
	"github.com/ChainSafe/gossamer/lib/crypto/sr25519"
	"github.com/ChainSafe/gossamer/pkg/scale"
)

type CandidateDescriptorVersion byte

const (
	//The old candidate descriptor version.
	CandidateDescriptorVersion1 CandidateDescriptorVersion = iota + 1

	// The new candidate descriptor version.
	CandidateDescriptorVersion2
)

var ErrUnknownCandidateDescriptorVersion = fmt.Errorf("unknown candidate descriptor version")

const defaultClaimQueueOffset byte = 0

// errors when checking committed candidate receipt
var (
	ErrCoreIndexMismatch            = errors.New("core index in commitments doesn't match the one in descriptor") //nolint:lll
	ErrCoreSelectorWithV1Descriptor = errors.New("core selector with v1 descriptor")
	ErrNoCoresAssigned              = errors.New("parachain is not assigned to any core at specified claim queue offset") //nolint:lll
	ErrInvalidCoreIndex             = errors.New("invalid core index")
)

// CandidateDescriptorV2 is a descriptor for a parachain candidate.
// NOTE: This type is backward compatible with CandidateDescriptor.
type CandidateDescriptorV2 struct {
	// The ID of the para this is a candidate for.
	ParaID ParaID
	// RelayParent is the hash of the relay-chain block this should be executed in
	// the context of.
	RelayParent common.Hash
	// CurrentVersion is a raw value used internally by the `Version()` method to determine the
	// `CandidateDescriptorVersion`. This field should not be used directly anywhere else in the code.
	// For version 2, this field is set to `0` and will be incremented by subsequent versions.
	CurrentVersion uint8
	// The core index where the candidate is backed.
	CoreIndex uint16
	// The session index of the candidate relay parent.
	SessionIndex SessionIndex
	// Reserved bytes.
	Reserved1 [25]uint8
	// PersistedValidationDataHash is the blake2-256 hash of the persisted validation data. This is extra data derived from
	// relay-chain state which may vary based on bitfields included before the candidate.
	// Thus, it cannot be derived entirely from the relay-parent.
	PersistedValidationDataHash common.Hash
	// PovHash is the hash of the `pov-block`.
	PovHash common.Hash
	// ErasureRoot is the root of a block's erasure encoding Merkle tree.
	ErasureRoot common.Hash
	// Reserved bytes.
	Reserved2 [64]uint8
	// ParaHead is the hash of the para header that is being generated by this candidate.
	ParaHead common.Hash
	// ValidationCodeHash is the blake2-256 hash of the validation code bytes.
	ValidationCodeHash ValidationCodeHash
}

func (cd CandidateDescriptorV2) Version() (CandidateDescriptorVersion, error) {
	var zeroReserved1 [25]byte
	var zeroReserved2 [64]byte

	isReserved1Empty := bytes.Equal(cd.Reserved1[:], zeroReserved1[:])
	isReserved2Empty := bytes.Equal(cd.Reserved2[:], zeroReserved2[:])

	if !isReserved1Empty || !isReserved2Empty {
		return CandidateDescriptorVersion1, nil
	}

	// for version 2 the CurrentVersion field is zero and will be incremented by subsequent versions.
	if cd.CurrentVersion == 0 {
		return CandidateDescriptorVersion2, nil
	}

	return CandidateDescriptorVersion(0), fmt.Errorf("%w %d", ErrUnknownCandidateDescriptorVersion, cd.CurrentVersion+2)
}

func (cd CandidateDescriptorV2) CreateSignaturePayload() ([]byte, error) {
	var payload [132]byte
	copy(payload[0:32], cd.RelayParent.ToBytes())

	buffer := bytes.NewBuffer(nil)
	encoder := scale.NewEncoder(buffer)
	err := encoder.Encode(cd.ParaID)
	if err != nil {
		return nil, fmt.Errorf("encoding parachain id: %w", err)
	}
	if len(buffer.Bytes()) != 4 {
		return nil, fmt.Errorf("invalid length of encoded parachain id")
	}
	copy(payload[32:36], buffer.Bytes())
	copy(payload[36:68], cd.PersistedValidationDataHash.ToBytes())
	copy(payload[68:100], cd.PovHash.ToBytes())
	copy(payload[100:132], common.Hash(cd.ValidationCodeHash).ToBytes())

	return payload[:], nil
}

// CheckCollatorSignature checks the signature of the collator
// NOTE: This method is only used for the candidate descriptor version 1.
func (cd CandidateDescriptorV2) CheckCollatorSignature() error {
	descriptorVersion, err := cd.Version()
	if err != nil {
		return fmt.Errorf("getting descriptor version: %w", err)
	}

	// return early if descriptor version is not CandidateDescriptorVersion1
	if descriptorVersion != CandidateDescriptorVersion1 {
		return nil
	}

	collator := cd.RebuildCollatorField()
	signature := cd.RebuilSignatureField()

	payload, err := cd.CreateSignaturePayload()
	if err != nil {
		return fmt.Errorf("creating signature payload: %w", err)
	}

	return sr25519.VerifySignature(collator[:], signature[:], payload)
}

// RebuildCollatorField reconstructs the CollatorID from the CandidateDescriptorV2 fields.
// Note: This field was present in version 1 but has been removed in version 2.
func (cd CandidateDescriptorV2) RebuildCollatorField() CollatorID {
	var collator CollatorID
	sessionIndex := uint32(cd.SessionIndex)

	collator[0] = cd.CurrentVersion                            // 1 byte
	binary.NativeEndian.PutUint16(collator[1:3], cd.CoreIndex) // 2 bytes
	binary.NativeEndian.PutUint32(collator[3:7], sessionIndex) // 4 bytes
	copy(collator[7:32], cd.Reserved1[:])                      // 25 bytes (fix: ensure correct range)

	return collator
}

// RebuilSignatureField reconstructs the CollatorSignature from the CandidateDescriptorV2 fields.
// Note: This field was present in version 1 but has been removed in version 2.
func (cd CandidateDescriptorV2) RebuilSignatureField() CollatorSignature {
	return cd.Reserved2
}

// V2 converts a CandidateDescriptor to a CandidateDescriptorV2
func (cdV1 CandidateDescriptor) V2() CandidateDescriptorV2 {
	// use first byte of collator as version
	version := cdV1.Collator[0] // 1 byte from collator
	// next two bytes of collator are core index
	coreIndex := binary.NativeEndian.Uint16(cdV1.Collator[1:3]) // next 2 bytes from collator
	// next four bytes of collator are session index
	sessionIndex := SessionIndex(binary.NativeEndian.Uint32(cdV1.Collator[3:7])) // next 4 bytes from collator
	// use remaining 25 bytes as reserved1
	var reserved1 [25]byte
	copy(reserved1[:], cdV1.Collator[7:]) // remaining 25 bytes from collator

	// use collator signature as reserved2
	var reserved2 [64]byte = cdV1.Signature

	return CandidateDescriptorV2{
		ParaID:                      cdV1.ParaID,
		RelayParent:                 cdV1.RelayParent,
		CurrentVersion:              version,
		CoreIndex:                   coreIndex,
		SessionIndex:                sessionIndex,
		Reserved1:                   reserved1,
		PersistedValidationDataHash: cdV1.PersistedValidationDataHash,
		PovHash:                     cdV1.PovHash,
		ErasureRoot:                 cdV1.ErasureRoot,
		Reserved2:                   reserved2,
		ParaHead:                    cdV1.ParaHead,
		ValidationCodeHash:          cdV1.ValidationCodeHash,
	}
}

// CommittedCandidateReceiptV2 is a candidate-receipt with commitments directly included.
// NOTE: This type is backward compatible with CommittedCandidateReceipt.
type CommittedCandidateReceiptV2 struct {
	// The descriptor of the candidate.
	Descriptor CandidateDescriptorV2 `scale:"1"`
	// The commitments of the candidate receipt.
	Commitments CandidateCommitments `scale:"2"`
}

// ToPlain converts a CommittedCandidateReceiptV2 to a CandidateReceiptV2
func (ccr CommittedCandidateReceiptV2) ToPlain() CandidateReceiptV2 {
	return CandidateReceiptV2{
		Descriptor:      ccr.Descriptor,
		CommitmentsHash: ccr.Commitments.Hash(),
	}
}

// Hash returns the hash of the CommittedCandidateReceiptV2
func (ccr CommittedCandidateReceiptV2) Hash() (common.Hash, error) {
	return ccr.ToPlain().Hash()
}

// CheckCoreIndex checks if descriptor core index is equal to the committed core index.
// Input `coresPerPara` is a claim queue snapshot at the candidate's relay parent, stored as
// a mapping between `ParaId` and the cores assigned per depth
func (ccr CommittedCandidateReceiptV2) CheckCoreIndex(coresPerPara TransposedClaimQueue) error {
	selectCore, err := ccr.Commitments.CoreSelector()
	if err != nil {
		return fmt.Errorf("getting core selector: %w", err)
	}

	descriptorVersion, err := ccr.Descriptor.Version()
	if err != nil {
		return fmt.Errorf("getting descriptor version: %w", err)
	}

	if descriptorVersion == CandidateDescriptorVersion1 {
		// If the parachain runtime started sending core selectors, v1 descriptors are no longer allowed
		if selectCore != nil {
			return ErrCoreSelectorWithV1Descriptor
		}
		return nil
	}

	// Default claim queue offset if no core selector
	claimQueueOffset := defaultClaimQueueOffset
	var coreIndexSelector *byte

	if selectCore != nil {
		coreIndexSelector = &selectCore.CoreSelector
		claimQueueOffset = selectCore.ClaimQueueOffset
	}

	// Get assigned cores for the parachain at the specified claim queue offset
	assignedCoreSet, assignedCoresSorted := coresPerPara.Cores(ccr.Descriptor.ParaID, claimQueueOffset)
	numOfCores := len(assignedCoresSorted)

	if numOfCores == 0 {
		return ErrNoCoresAssigned
	}

	descriptorCoreIndex := CoreIndex{Index: uint32(ccr.Descriptor.CoreIndex)}

	// Handle case with no core selector
	if coreIndexSelector == nil {
		if numOfCores > 1 {
			// Check if descriptor core index is among assigned cores
			if _, exists := assignedCoreSet[descriptorCoreIndex]; !exists {
				return fmt.Errorf("%w: %d", ErrInvalidCoreIndex, descriptorCoreIndex)
			}

			// the descriptor core index is indeed assigned to the parachain.
			return nil
		}

		// No core selector but only one assigned core, use index 0
		coreIndexSelector = new(byte)
		*coreIndexSelector = 0
	}

	// Get the core index from assigned cores using selector
	selectedIdx := int(*coreIndexSelector) % numOfCores

	coreIndex := assignedCoresSorted[selectedIdx]
	if coreIndex != descriptorCoreIndex {
		return fmt.Errorf("%w; in commitments: %d, in descriptor: %d",
			ErrCoreIndexMismatch, coreIndex, descriptorCoreIndex)
	}

	return nil
}

func (ccrV1 CommittedCandidateReceipt) V2() CommittedCandidateReceiptV2 {
	return CommittedCandidateReceiptV2{
		Descriptor:  ccrV1.Descriptor.V2(),
		Commitments: ccrV1.Commitments,
	}
}

// CandidateReceiptV2 A receipt for a parachain candidate.
// NOTE: This type is backward compatible with CandidateReceipt.
type CandidateReceiptV2 struct {
	// The candidate descriptor
	Descriptor CandidateDescriptorV2 `scale:"1"`
	// The candidate event.
	CommitmentsHash common.Hash `scale:"2"`
}

func (cr CandidateReceiptV2) Hash() (common.Hash, error) {
	bytes, err := scale.Marshal(cr)
	if err != nil {
		return common.Hash{}, fmt.Errorf("marshalling CandidateReceiptV2: %w", err)
	}

	return common.Blake2bHash(bytes)
}

// V2 converts a CandidateReceipt to a CandidateReceiptV2
func (crV1 CandidateReceipt) V2() CandidateReceiptV2 {
	crV2 := CandidateReceiptV2{
		Descriptor:      crV1.Descriptor.V2(),
		CommitmentsHash: crV1.CommitmentsHash,
	}

	return crV2
}

// SelectCore is a message sent by a parachain to select the core the candidate is committed to.
// Relay chain validators, in particular backers, use the `CoreSelector` and
// `ClaimQueueOffset` to compute the index of the core the candidate has committed to.
type SelectCore struct {
	CoreSelector     byte `scale:"1"`
	ClaimQueueOffset byte `scale:"2"`
}

// UMPSignal represents a signal that a parachain can send to the relay chain via the UMP queue.
type UMPSignal struct {
	inner any
}

type UMPSignalValues interface {
	SelectCore
}

func setUMPSignal[Value UMPSignalValues](mvdt *UMPSignal, value Value) {
	mvdt.inner = value
}

func (mvdt *UMPSignal) SetValue(value any) (err error) {
	switch value := value.(type) {
	case SelectCore:
		setUMPSignal(mvdt, value)
		return
	default:
		return fmt.Errorf("unsupported type")
	}
}

func (mvdt UMPSignal) IndexValue() (index uint, value any, err error) {
	switch mvdt.inner.(type) {
	case SelectCore:
		return 0, mvdt.inner, nil
	}
	return 0, nil, scale.ErrUnsupportedVaryingDataTypeValue
}

func (mvdt UMPSignal) Value() (value any, err error) {
	_, value, err = mvdt.IndexValue()
	return
}

func (mvdt UMPSignal) ValueAt(index uint) (value any, err error) {
	switch index {
	case 0:
		return SelectCore{}, nil
	}
	return nil, scale.ErrUnknownVaryingDataTypeValue
}
