version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: gometalinter ./...

      
workflows:
  version: 2
  build:
    jobs:
      - build
        filters:
          branches:
            only:
              development

