{
 "title": "Gossamer",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Goroutines",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{instance=~\".*gossamer.*\"}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_threads{instance=~\".*gossamer.*\"}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\".*gossamer.*\"}",
     "legendFormat": "Resident memory"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\".*gossamer.*\"}",
     "legendFormat": "Heap"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{instance=~\".*gossamer.*\"}",
     "legendFormat": "Heap Idle Bytes"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=~\".*gossamer.*\"}",
     "legendFormat": "Stack"
    }
   ]
  },
  {
   "title": "In Memory Runtimes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gossamer_inmemory_runtimes_total{instance=~\".*gossamer.*\"}",
     "legendFormat": "Runtimes"
    }
   ]
  },
  { "title": "Top", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Blocks synced",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gossamer_network_syncer_blocks_synced_total",
     "legendFormat": "Blocks synced"
    }
   ]
  },
  {
   "title": "Sync status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gossamer_network_syncer_is_synced",
     "legendFormat": "Inbound total"
    }
   ]
  },
  { "title": "State tries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Number of tries in memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "gossamer_storage_tries_set_total - gossamer_storage_tries_delete_total",
     "legendFormat": "Tries in memory"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Peers count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gossamer_network_node_peer_count_total",
     "legendFormat": "Peers count"
    }
   ]
  },
  {
   "title": "Connections count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gossamer_network_node_connections_total",
     "legendFormat": "Peers count"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gossamer_network_node_latency_ms",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Messages traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "gossamer_network_streams_inbound_total",
     "legendFormat": "Inbound total"
    },
    {
     "expr": "gossamer_network_streams_outbound_total",
     "legendFormat": "Outbounds total"
    }
   ]
  },
  {
   "title": "Block announce messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "gossamer_network_streams_block_announce_inbound_total",
     "legendFormat": "Inbound"
    },
    {
     "expr": "gossamer_network_streams_block_announce_outbound_total",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Grandpa messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "gossamer_network_streams_grandpa_inbound_total",
     "legendFormat": "Inbound"
    },
    {
     "expr": "gossamer_network_streams_grandpa_outbound_total",
     "legendFormat": "Outbount"
    }
   ]
  },
  { "title": "State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Number of transactions in pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "gossamer_state_transaction_pool_total",
     "legendFormat": "Transactions in pool"
    }
   ]
  },
  {
   "title": "Number of queued transactions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "gossamer_state_transaction_queue_total",
     "legendFormat": "Queued transactions"
    }
   ]
  },
  { "title": "Grandpa", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Grandpa round",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 62 },
   "targets": [
    { "expr": "gossamer_grandpa_round", "legendFormat": "Grandpa round" }
   ]
  },
  {
   "title": "Block leaves total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 62 },
   "targets": [
    { "expr": "gossamer_block_leaves_total", "legendFormat": "Block leaves total" }
   ]
  }
 ]
}