// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SyncAPI is an autogenerated mock type for the SyncAPI type
type SyncAPI struct {
	mock.Mock
}

// HighestBlock provides a mock function with given fields:
func (_m *SyncAPI) HighestBlock() int64 {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}
