// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	network "github.com/ChainSafe/gossamer/dot/network"
	"github.com/ChainSafe/gossamer/dot/peerset"
	"github.com/libp2p/go-libp2p-core/peer"
	mock "github.com/stretchr/testify/mock"
)

// MockNetwork is an autogenerated mock type for the Network type
type MockNetwork struct {
	mock.Mock
}

func (_m *MockNetwork) ReportPeer(_a0 peerset.ReputationChange, _a1 peer.ID) {
	return // TODO: figure how to implement here
}

// GossipMessage provides a mock function with given fields: _a0
func (_m *MockNetwork) GossipMessage(_a0 network.NotificationsMessage) {
	_m.Called(_a0)
}

// IsSynced provides a mock function with given fields:
func (_m *MockNetwork) IsSynced() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
