// Copyright 2025 ChainSafe Systems (ON)
// SPDX-License-Identifier: LGPL-3.0-only

//nolint:unused
package statementdistribution

import (
	"errors"
	"fmt"
	"slices"

	parachaintypes "github.com/ChainSafe/gossamer/dot/parachain/types"
	"github.com/ChainSafe/gossamer/lib/common"
	"github.com/libp2p/go-libp2p/core/peer"
)

var errBadAdvertisement = errors.New("bad advertisement")

// postConfirmationReckoning encapsulates the correct and incorrect advertisers
// post-confirmation of a candidate.
type postConfirmationReckoning struct {
	// Peers which advertised correctly.
	correct map[peer.ID]struct{}
	// Peers which advertised the candidate incorrectly.
	incorrect map[peer.ID]struct{}
}

func newPostConfirmationReckoning() *postConfirmationReckoning {
	return &postConfirmationReckoning{
		correct:   make(map[peer.ID]struct{}),
		incorrect: make(map[peer.ID]struct{}),
	}
}

// PostConfirmation outputs generated by initial confirmation of a candidate.
type postConfirmation struct {
	// The hypothetical candidate used to determine importability and membership
	// in the hypothetical frontier.
	hypothetical parachaintypes.HypotheticalCandidate
	// A "reckoning" of peers who have advertised the candidate previously,
	// either accurately or inaccurately.
	reckoning *postConfirmationReckoning
}

type hashAndParaID struct {
	Hash   common.Hash
	ParaID parachaintypes.ParaID
}

// A tracker for all known candidates in the view.
type candidates struct {
	candidates map[parachaintypes.CandidateHash]candidateState
	byParent   map[hashAndParaID]map[parachaintypes.CandidateHash]struct{}
}

func (c *candidates) isConfirmed(candidateHash parachaintypes.CandidateHash) bool {
	if _, ok := c.candidates[candidateHash]; ok {
		_, ok := c.candidates[candidateHash].(*confirmedCandidate)
		return ok
	}

	return false
}

// getConfirmed retrieves a confirmed candidate by its hash.
// It returns the confirmed candidate and a boolean indicating whether it was found.
func (c *candidates) getConfirmed(candidateHash parachaintypes.CandidateHash) (*confirmedCandidate, bool) {
	if state, ok := c.candidates[candidateHash]; ok {
		if confirmed, ok := state.(*confirmedCandidate); ok {
			return confirmed, true
		}
	}
	return nil, false
}

// isImportable returns whether statements from a candidate are importable.
// This is only true when the candidate is known, confirmed,
// and is importable in a fragment chain.
func (c *candidates) isImportable(candidateHash parachaintypes.CandidateHash) (isImportable bool) {
	if confirmed, ok := c.getConfirmed(candidateHash); ok {
		isImportable = confirmed.isImportable(nil)
	}

	return isImportable
}

// noteImportableUnder notes that a candidate is importable in a fragment chain indicated by the given leaf hash.
func (c *candidates) noteImportableUnder(candidate parachaintypes.HypotheticalCandidate, leafHash common.Hash) {
	switch candidate := candidate.(type) {
	case parachaintypes.HypotheticalCandidateComplete:
		if candidateState, ok := c.candidates[candidate.ClaimedCandidateHash]; ok {
			if confirmedCandidate, ok := candidateState.(*confirmedCandidate); ok {
				confirmedCandidate.importableUnder[leafHash] = struct{}{}
			}
		}
	case parachaintypes.HypotheticalCandidateIncomplete:
		if candidateState, ok := c.candidates[candidate.ClaimedCandidateHash]; ok {
			if confirmedCandidate, ok := candidateState.(*unconfirmedCandidate); ok {
				u := unconfirmedImportable{
					relayParent: candidate.RelayParent,
					parentHash:  candidate.ParentHeadDataHash,
					paraID:      candidate.CandidateParaID,
				}

				confirmedCandidate.noteMaybeImportableUnder(leafHash, u)
			}
		}
	default:
		panic(fmt.Sprintf("unexpected candidate type %T", candidate))
	}
}

// confirmCandidate notes that a candidate has been confirmed. If the candidate has just been
// confirmed (previous state was Unconfirmed), then this returns a non-nil PostConfirmation. Otherwise, nil.
//
// If we are confirming for the first time, then remove any outdated claims, and generate a
// reckoning of which peers advertised correctly and incorrectly.
//
// This does no sanity-checking of input data, and will overwrite already-confirmed candidates.
func (c *candidates) confirmCandidate(
	candidateHash parachaintypes.CandidateHash,
	candidateReceipt parachaintypes.CommittedCandidateReceiptV2,
	persistedValidationData parachaintypes.PersistedValidationData,
	assignedGroup parachaintypes.GroupIndex, //nolint:unparam
) (*postConfirmation, error) {
	parentHash, err := persistedValidationData.ParentHead.Hash()
	if err != nil {
		return nil, fmt.Errorf("failed to get parent head hash: %w", err)
	}
	relayParent := candidateReceipt.Descriptor.RelayParent
	paraID := candidateReceipt.Descriptor.ParaID

	prevState, hadPrev := c.candidates[candidateHash]

	newConfirmed := &confirmedCandidate{
		receipt:         candidateReceipt,
		pvd:             &persistedValidationData,
		assignedGroup:   assignedGroup,
		parentHash:      parentHash,
		importableUnder: make(map[common.Hash]struct{}),
	}
	c.candidates[candidateHash] = newConfirmed

	// Update byParent index
	key := hashAndParaID{Hash: parentHash, ParaID: paraID}
	if _, ok := c.byParent[key]; !ok {
		c.byParent[key] = make(map[parachaintypes.CandidateHash]struct{})
	}
	c.byParent[key][candidateHash] = struct{}{}

	if !hadPrev {
		// No previous state
		return &postConfirmation{
			reckoning:    newPostConfirmationReckoning(),
			hypothetical: newConfirmed.toHypothetical(candidateHash),
		}, nil
	}

	switch prev := prevState.(type) {
	case *confirmedCandidate:
		// Already confirmed
		return nil, nil
	case *unconfirmedCandidate:
		reckoning := newPostConfirmationReckoning()

		// Transfer importable_under
		for entry := range prev.unconfirmedImportableUnder {
			if entry.unconfirmed.relayParent == relayParent &&
				entry.unconfirmed.parentHash == parentHash &&
				entry.unconfirmed.paraID == paraID {
				newConfirmed.importableUnder[entry.hash] = struct{}{}
			}
		}

		for _, claim := range prev.claims {
			// Update the by-parent-hash index not to store any outdated
			// claims.
			if claim.claims.parentHashAndId != nil {
				claimedParentHash := claim.claims.parentHashAndId.Hash
				claimedParaID := claim.claims.parentHashAndId.ParaID
				if claimedParentHash != parentHash || claimedParaID != paraID {
					k := hashAndParaID{Hash: claimedParentHash, ParaID: claimedParaID}
					if e, ok := c.byParent[k]; ok {
						delete(e, candidateHash)
						if len(e) == 0 {
							delete(c.byParent, k)
						}
					}
				}
			}

			if claim.claims.check(relayParent, assignedGroup, parentHash, paraID) {
				reckoning.correct[claim.peerID] = struct{}{}
			} else {
				reckoning.incorrect[claim.peerID] = struct{}{}
			}
		}

		return &postConfirmation{
			reckoning:    reckoning,
			hypothetical: newConfirmed.toHypothetical(candidateHash),
		}, nil
	default:
		panic(fmt.Sprintf("expected unconfirmed or confirmed candidate, got %T", prevState))
	}
}

// insertUnconfirmed inserts an advertisement.
//
// This should be invoked only after performing
// spam protection and only for advertisements that
// are valid within the current view. [`Candidates`] never prunes
// candidate by peer ID, to avoid peers skirting misbehaviour
// reports by disconnecting intermittently. Therefore, this presumes
// that spam protection limits the peers which can send advertisements
// about unconfirmed candidates.
//
// It returns error incase that the candidate is
// already known and reality conflicts with the advertisement.
func (c *candidates) insertUnconfirmed(
	peerID peer.ID,
	candidateHash parachaintypes.CandidateHash,
	claimedRelayParent common.Hash,
	claimedGroupIndex parachaintypes.GroupIndex,
	claimedParentHashAndParaID *hashAndParaID,
) error {
	state, ok := c.candidates[candidateHash]
	if !ok {
		state = &unconfirmedCandidate{
			claims:                     []peerIDAndClaims{},
			parentClaims:               make(map[hashAndParaID]map[common.Hash]uint),
			unconfirmedImportableUnder: make(map[hashAndUnconfirmed]struct{}),
		}
		c.candidates[candidateHash] = state
	}

	switch s := state.(type) {
	case *confirmedCandidate:
		if s.receipt.Descriptor.RelayParent != claimedRelayParent {
			return fmt.Errorf("%w: relay-parent mismatch: expected %s, got %s",
				errBadAdvertisement, s.receipt.Descriptor.RelayParent, claimedRelayParent)
		}

		if s.assignedGroup != claimedGroupIndex {
			return fmt.Errorf("%w: group index mismatch: expected %d, got %d",
				errBadAdvertisement, s.assignedGroup, claimedGroupIndex)
		}

		if claimedParentHashAndParaID != nil {
			if s.parentHash != claimedParentHashAndParaID.Hash {
				return fmt.Errorf("%w: parent hash mismatch: expected %s, got %s",
					errBadAdvertisement, s.parentHash, claimedParentHashAndParaID.Hash)
			}

			if s.receipt.Descriptor.ParaID != claimedParentHashAndParaID.ParaID {
				return fmt.Errorf("%w: para ID mismatch: expected %d, got %d",
					errBadAdvertisement, s.receipt.Descriptor.ParaID, claimedParentHashAndParaID.ParaID)
			}
		}

	case *unconfirmedCandidate:
		s.addClaims(peerID, candidateClaims{
			relayParent:     claimedRelayParent,
			groupIndex:      claimedGroupIndex,
			parentHashAndId: claimedParentHashAndParaID,
		})

		if claimedParentHashAndParaID != nil {
			candidateHashes, ok := c.byParent[*claimedParentHashAndParaID]
			if !ok {
				candidateHashes = make(map[parachaintypes.CandidateHash]struct{})
				c.byParent[*claimedParentHashAndParaID] = candidateHashes
			}
			candidateHashes[candidateHash] = struct{}{}
		}
	default:
		panic(fmt.Sprintf("expected unconfirmed or confirmed candidate, got %T", state))
	}

	return nil
}

type candidateHashAndState struct {
	cHash parachaintypes.CandidateHash
	state candidateState
}

// frontierHypotheticals returns all hypothetical candidates which should be tested
// for inclusion in the frontier. If parent is provided, only candidates that are
// potential children of that parent are included.
func (c *candidates) frontierHypotheticals(parent *hashAndParaID) []parachaintypes.HypotheticalCandidate {
	extendHypotheticals := func(
		v []parachaintypes.HypotheticalCandidate,
		i []candidateHashAndState,
		maybeRequiredParent *hashAndParaID,
	) []parachaintypes.HypotheticalCandidate {
		for _, entry := range i {
			switch candidate := entry.state.(type) {
			case *unconfirmedCandidate:
				v = candidate.extendHypotheticals(entry.cHash, v, maybeRequiredParent)
			case *confirmedCandidate:
				v = append(v, candidate.toHypothetical(entry.cHash))
			}
		}

		return v
	}

	var v []parachaintypes.HypotheticalCandidate

	if parent != nil {
		maybeChildren, ok := c.byParent[*parent]
		i := make([]candidateHashAndState, 0, len(maybeChildren))
		if ok {
			for cHash := range maybeChildren {
				if state, ok := c.candidates[cHash]; ok {
					i = append(i, candidateHashAndState{cHash: cHash, state: state})
				}
			}
		}
		v = extendHypotheticals(v, i, parent)
	} else {
		i := make([]candidateHashAndState, 0, len(c.candidates))
		for cHash, state := range c.candidates {
			i = append(i, candidateHashAndState{cHash: cHash, state: state})
		}
		v = extendHypotheticals(v, i, nil)
	}

	return v
}

// onDeactivateLeaves prunes all candidates according to the relay-parent predicate provided.
func (c *candidates) onDeactivateLeaves(leaves []common.Hash, relayParentLive func(common.Hash) bool) {
	removeParentClaims := func(cHash parachaintypes.CandidateHash, parentHash common.Hash, id parachaintypes.ParaID) {
		k := hashAndParaID{Hash: parentHash, ParaID: id}
		if e, ok := c.byParent[k]; ok {
			delete(e, cHash)
			if len(e) == 0 {
				delete(c.byParent, k)
			}
		}
	}

	newCandidates := make(map[parachaintypes.CandidateHash]candidateState, len(c.candidates))
	for cHash, state := range c.candidates {
		switch s := state.(type) {
		case *confirmedCandidate:
			// relayParent is the relay-parent hash for this candidate
			relayParent := s.receipt.Descriptor.RelayParent
			if !relayParentLive(relayParent) {
				removeParentClaims(cHash, s.parentHash, s.receipt.Descriptor.ParaID)
				// prune
				continue
			}
			// Remove importable_under for deactivated leaves
			for _, leafHash := range leaves {
				delete(s.importableUnder, leafHash)
			}
			newCandidates[cHash] = s
		case *unconfirmedCandidate:
			s.onDeactivateLeaves(
				leaves,
				func(parentHash common.Hash, id parachaintypes.ParaID) {
					removeParentClaims(cHash, parentHash, id)
				},
				relayParentLive,
			)
			if s.hasClaims() {
				newCandidates[cHash] = s
			}
		}
	}
	c.candidates = newCandidates

	logger.Tracef("candidates remaining after cleanup: %d", len(c.candidates))
}

// candidateState represents the state of a candidate: unconfirmed or confirmed.
type candidateState interface {
	isCandidateState()
}

var (
	_ candidateState = (*unconfirmedCandidate)(nil)
	_ candidateState = (*confirmedCandidate)(nil)
)

// candidateClaims claims made alongside the advertisement of a candidate.
type candidateClaims struct {
	// The relay-parent committed to by the candidate.
	relayParent common.Hash

	// The group index assigned to this candidate.
	groupIndex parachaintypes.GroupIndex

	// The hash of the parent head-data and the ParaId. This is optional,
	// as only some types of advertisements include this data.
	parentHashAndId *hashAndParaID
}

func (c *candidateClaims) check(
	rpHash common.Hash,
	groupIndex parachaintypes.GroupIndex,
	parentHash common.Hash,
	paraID parachaintypes.ParaID,
) bool {
	return c.relayParent == rpHash &&
		c.groupIndex == groupIndex &&
		(c.parentHashAndId == nil ||
			(c.parentHashAndId.Hash == parentHash && c.parentHashAndId.ParaID == paraID))
}

// unconfirmedImportable properties of an unconfirmed but hypothetically importable candidate.
type unconfirmedImportable struct {
	relayParent common.Hash
	parentHash  common.Hash
	paraID      parachaintypes.ParaID
}

type peerIDAndClaims struct {
	peerID peer.ID
	claims candidateClaims
}

type hashAndUnconfirmed struct {
	hash        common.Hash
	unconfirmed unconfirmedImportable
}

// An unconfirmed candidate may have been advertised under
// multiple identifiers. We track here, on the basis of unique identifier,
// the peers which advertised each candidate in a specific way.
type unconfirmedCandidate struct {
	// claims maps each peer to their claims about the candidate.
	claims []peerIDAndClaims

	parentClaims               map[hashAndParaID]map[common.Hash]uint
	unconfirmedImportableUnder map[hashAndUnconfirmed]struct{}
}

func (u *unconfirmedCandidate) addClaims(peerID peer.ID, claims candidateClaims) {
	// This does no deduplication, but this is only called after
	// spam prevention is already done. In practice we expect that
	// each peer will be able to announce the same candidate about 1 time per live relay-parent,
	// but in doing so it limits the amount of other candidates it can advertise. on balance,
	// memory consumption is bounded in the same way.
	if claims.parentHashAndId != nil {
		subClaims, ok := u.parentClaims[*claims.parentHashAndId]
		if !ok {
			subClaims = make(map[common.Hash]uint)
			subClaims[claims.relayParent] = 0
		}

		subClaims[claims.relayParent] += 1
		u.parentClaims[*claims.parentHashAndId] = subClaims
	}

	u.claims = append(u.claims, peerIDAndClaims{peerID: peerID, claims: claims})
}

func (u *unconfirmedCandidate) noteMaybeImportableUnder(activeLeaf common.Hash, unconfirmed unconfirmedImportable) {
	u.unconfirmedImportableUnder[hashAndUnconfirmed{
		hash:        activeLeaf,
		unconfirmed: unconfirmed,
	}] = struct{}{}
}

func (u *unconfirmedCandidate) onDeactivateLeaves(
	leaves []common.Hash,
	removeParentIndex func(common.Hash, parachaintypes.ParaID),
	relayParentLive func(common.Hash) bool,
) {
	var claimsToRemove []int
	for idx, claim := range u.claims {
		if relayParentLive(claim.claims.relayParent) {
			continue
		}

		if claim.claims.parentHashAndId != nil {
			if e, ok := u.parentClaims[*claim.claims.parentHashAndId]; ok {
				if refCount, ok := e[claim.claims.relayParent]; ok {
					if refCount-1 == 0 {
						delete(e, claim.claims.relayParent)
					} else {
						e[claim.claims.relayParent]--
					}
				}

				if len(e) == 0 {
					removeParentIndex(claim.claims.parentHashAndId.Hash, claim.claims.parentHashAndId.ParaID)
					delete(u.parentClaims, *claim.claims.parentHashAndId)
				}
			}
		}

		claimsToRemove = append(claimsToRemove, idx)
	}

	for i := len(claimsToRemove) - 1; i >= 0; i-- {
		// Remove the claim at the index specified by claimsToRemove.
		// Iterating backwards to avoid invalidating indices as we remove elements.
		idx := claimsToRemove[i]
		u.claims = append(u.claims[:idx], u.claims[idx+1:]...)
	}

	for entry := range u.unconfirmedImportableUnder {
		if slices.Contains(leaves, entry.hash) && relayParentLive(entry.unconfirmed.relayParent) {
			continue
		}

		delete(u.unconfirmedImportableUnder, entry)
	}
}

func (u *unconfirmedCandidate) extendHypotheticals(
	candidateHash parachaintypes.CandidateHash,
	hypotheticalCandidates []parachaintypes.HypotheticalCandidate,
	requiredParent *hashAndParaID,
) []parachaintypes.HypotheticalCandidate {
	if requiredParent == nil {
		for key, possibleRelayParent := range u.parentClaims {
			for rp := range possibleRelayParent {
				hypotheticalCandidates = append(hypotheticalCandidates, &parachaintypes.HypotheticalCandidateIncomplete{
					ClaimedCandidateHash: candidateHash,
					CandidateParaID:      key.ParaID,
					ParentHeadDataHash:   key.Hash,
					RelayParent:          rp,
				})
			}
		}
	} else {
		if parentClaims, ok := u.parentClaims[*requiredParent]; ok {
			for rp := range parentClaims {
				hypotheticalCandidates = append(hypotheticalCandidates, &parachaintypes.HypotheticalCandidateIncomplete{
					ClaimedCandidateHash: candidateHash,
					CandidateParaID:      requiredParent.ParaID,
					ParentHeadDataHash:   requiredParent.Hash,
					RelayParent:          rp,
				})
			}
		}
	}

	return hypotheticalCandidates
}

func (u *unconfirmedCandidate) hasClaims() bool {
	return len(u.claims) > 0
}

func (*unconfirmedCandidate) isCandidateState() {}

type confirmedCandidate struct {
	receipt         parachaintypes.CommittedCandidateReceiptV2
	pvd             *parachaintypes.PersistedValidationData
	assignedGroup   parachaintypes.GroupIndex
	parentHash      common.Hash
	importableUnder map[common.Hash]struct{}
}

// isImportable returns whether the candidate is importable.
func (c *confirmedCandidate) isImportable(underActiveLeaf *common.Hash) bool {
	if underActiveLeaf == nil {
		return len(c.importableUnder) > 0
	}

	_, ok := c.importableUnder[*underActiveLeaf]
	return ok
}

func (c *confirmedCandidate) toHypothetical(
	candidateHash parachaintypes.CandidateHash,
) parachaintypes.HypotheticalCandidate {
	return &parachaintypes.HypotheticalCandidateComplete{
		ClaimedCandidateHash:      candidateHash,
		CommittedCandidateReceipt: c.receipt,
		PersistedValidationData:   *c.pvd,
	}
}

func (*confirmedCandidate) isCandidateState() {}
