// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ChainSafe/gossamer/dot/parachain/statement-distribution (interfaces: clusterTracker)
//
// Generated by this command:
//
//	mockgen -destination=mocks_cluster_tracker_test.go -package=statementdistribution . clusterTracker
//

// Package statementdistribution is a generated GoMock package.
package statementdistribution

import (
	reflect "reflect"

	parachaintypes "github.com/ChainSafe/gossamer/dot/parachain/types"
	common "github.com/ChainSafe/gossamer/lib/common"
	gomock "go.uber.org/mock/gomock"
)

// MockclusterTracker is a mock of clusterTracker interface.
type MockclusterTracker struct {
	ctrl     *gomock.Controller
	recorder *MockclusterTrackerMockRecorder
	isgomock struct{}
}

// MockclusterTrackerMockRecorder is the mock recorder for MockclusterTracker.
type MockclusterTrackerMockRecorder struct {
	mock *MockclusterTracker
}

// NewMockclusterTracker creates a new mock instance.
func NewMockclusterTracker(ctrl *gomock.Controller) *MockclusterTracker {
	mock := &MockclusterTracker{ctrl: ctrl}
	mock.recorder = &MockclusterTrackerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockclusterTracker) EXPECT() *MockclusterTrackerMockRecorder {
	return m.recorder
}

// noteSend mocks base method.
func (m *MockclusterTracker) noteSend(target, originator parachaintypes.ValidatorIndex, stmt parachaintypes.CompactStatement) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "noteSend", target, originator, stmt)
}

// noteSend indicates an expected call of noteSend.
func (mr *MockclusterTrackerMockRecorder) noteSend(target, originator, stmt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "noteSend", reflect.TypeOf((*MockclusterTracker)(nil).noteSend), target, originator, stmt)
}

// pendingStatementsFor mocks base method.
func (m *MockclusterTracker) pendingStatementsFor(target parachaintypes.ValidatorIndex) []originatorStatementPair {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "pendingStatementsFor", target)
	ret0, _ := ret[0].([]originatorStatementPair)
	return ret0
}

// pendingStatementsFor indicates an expected call of pendingStatementsFor.
func (mr *MockclusterTrackerMockRecorder) pendingStatementsFor(target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "pendingStatementsFor", reflect.TypeOf((*MockclusterTracker)(nil).pendingStatementsFor), target)
}

// warningIfTooManyPendingStatements mocks base method.
func (m *MockclusterTracker) warningIfTooManyPendingStatements(rp common.Hash) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "warningIfTooManyPendingStatements", rp)
}

// warningIfTooManyPendingStatements indicates an expected call of warningIfTooManyPendingStatements.
func (mr *MockclusterTrackerMockRecorder) warningIfTooManyPendingStatements(rp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "warningIfTooManyPendingStatements", reflect.TypeOf((*MockclusterTracker)(nil).warningIfTooManyPendingStatements), rp)
}
