// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ChainSafe/gossamer/dot/parachain/statement-distribution (interfaces: candidatesStore)
//
// Generated by this command:
//
//	mockgen -destination=mocks_candidates_store_test.go -package=statementdistribution . candidatesStore
//

// Package statementdistribution is a generated GoMock package.
package statementdistribution

import (
	reflect "reflect"

	parachaintypes "github.com/ChainSafe/gossamer/dot/parachain/types"
	gomock "go.uber.org/mock/gomock"
)

// MockcandidatesStore is a mock of candidatesStore interface.
type MockcandidatesStore struct {
	ctrl     *gomock.Controller
	recorder *MockcandidatesStoreMockRecorder
	isgomock struct{}
}

// MockcandidatesStoreMockRecorder is the mock recorder for MockcandidatesStore.
type MockcandidatesStoreMockRecorder struct {
	mock *MockcandidatesStore
}

// NewMockcandidatesStore creates a new mock instance.
func NewMockcandidatesStore(ctrl *gomock.Controller) *MockcandidatesStore {
	mock := &MockcandidatesStore{ctrl: ctrl}
	mock.recorder = &MockcandidatesStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcandidatesStore) EXPECT() *MockcandidatesStoreMockRecorder {
	return m.recorder
}

// getConfirmed mocks base method.
func (m *MockcandidatesStore) getConfirmed(candidateHash parachaintypes.CandidateHash) (*confirmedCandidate, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getConfirmed", candidateHash)
	ret0, _ := ret[0].(*confirmedCandidate)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// getConfirmed indicates an expected call of getConfirmed.
func (mr *MockcandidatesStoreMockRecorder) getConfirmed(candidateHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getConfirmed", reflect.TypeOf((*MockcandidatesStore)(nil).getConfirmed), candidateHash)
}
