name: User story
description: Create a user story
title: "User story: FILL-ME-PLEASE"
body:
  - type: dropdown
    id: role
    attributes:
      label: As a
      options:
        - Polkadot implementer (Default)
        - Polkadot node operator
        - Blockchain developer
        - Dapp developer
        - Authority node in a parachain
        - Relay node in a relay chain
      description: |
        Describe the role you would play for this user story.
    validations:
      required: true
  - type: textarea
    id: wantto
    attributes:
      label: I want to
      placeholder: "Develop this new feature and change this"
      render: markdown
    validations:
      required: true
  - type: textarea
    id: because
    attributes:
      label: Because
      placeholder: "Because I need to do something"
      render: markdown
    validations:
      required: true
