[global]
name = "ksmcc"
id = "ksmcc"
datadir = "~/.gossamer/ksmcc"

[account]
key = ""
unlock = ""

[core]
authority = false
roles = 1

[network]
port = 7001
bootnodes = []
protocol = "/gossamer/ksmcc/0"
nobootstrap = false
nomdns = false

[rpc]
enabled = false
port = 8545
host = "localhost"
modules = ["system"]

[init]
genesis = "./node/ksmcc/genesis.json"
