[global]
name = "ksmcc"
id = "ksmcc"
config = "./node/ksmcc/config.toml"
genesis = "./node/ksmcc/genesis.json"
datadir = "~/.gossamer/ksmcc"

[account]
key = ""
unlock = ""

[core]
authority = false

[network]
port = 7001
bootnodes = []
protocol = "/gossamer/ksmcc/0"
roles = 1
nobootstrap = false
nomdns = false

[rpc]
enabled = false
port = 8545
host = "localhost"
modules = ["system"]
