// Code generated by mockery v2.8.0. DO NOT EDIT.

package grandpa

import (
	network "github.com/ChainSafe/gossamer/dot/network"
	mock "github.com/stretchr/testify/mock"

	peer "github.com/libp2p/go-libp2p-core/peer"

	protocol "github.com/libp2p/go-libp2p-core/protocol"
)

// MockNetwork is an autogenerated mock type for the Network type
type MockNetwork struct {
	mock.Mock
}

// RegisterNotificationsProtocol provides a mock function with given fields: sub, messageID, handshakeGetter, handshakeDecoder, handshakeValidator, messageDecoder, messageHandler, overwriteProtocol
func (_m *MockNetwork) RegisterNotificationsProtocol(sub protocol.ID, messageID byte, handshakeGetter func() (network.Handshake, error), handshakeDecoder func([]byte) (network.Handshake, error), handshakeValidator func(peer.ID, network.Handshake) error, messageDecoder func([]byte) (network.NotificationsMessage, error), messageHandler func(peer.ID, network.NotificationsMessage) (bool, error), overwriteProtocol bool) error {
	ret := _m.Called(sub, messageID, handshakeGetter, handshakeDecoder, handshakeValidator, messageDecoder, messageHandler, overwriteProtocol)

	var r0 error
	if rf, ok := ret.Get(0).(func(protocol.ID, byte, func() (network.Handshake, error), func([]byte) (network.Handshake, error), func(peer.ID, network.Handshake) error, func([]byte) (network.NotificationsMessage, error), func(peer.ID, network.NotificationsMessage) (bool, error), bool) error); ok {
		r0 = rf(sub, messageID, handshakeGetter, handshakeDecoder, handshakeValidator, messageDecoder, messageHandler, overwriteProtocol)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendJustificationRequest provides a mock function with given fields: to, num
func (_m *MockNetwork) SendJustificationRequest(to peer.ID, num uint32) {
	_m.Called(to, num)
}

// SendMessage provides a mock function with given fields: msg
func (_m *MockNetwork) SendMessage(msg network.NotificationsMessage) {
	_m.Called(msg)
}
