[global]
name = "ksmcc"
id = "ksmcc"
datadir = "~/.gossamer/ksmcc"

[init]
genesis = "./chain/ksmcc/genesis.json"

[account]
key = ""
unlock = ""

[core]
authority = false
roles = 1

[network]
port = 7001
bootnodes = []
protocol = "/gossamer/ksmcc/0"
nobootstrap = false
nomdns = false

[rpc]
enabled = false
port = 8545
host = "localhost"
modules = ["system"]
ws-port = 8546
ws-enabled = false
