[global]
name = "ksmcc"
id = "ksmcc"
basepath = "~/.gossamer/ksmcc"
log = "info"

[log]
core = ""
network = ""
rpc = ""
state = ""
runtime = ""
babe = ""
grandpa = ""

[init]
genesis-raw = "./chain/ksmcc/genesis-raw.json"

[account]
key = ""
unlock = ""

[core]
roles = 1
babe-authority = false
grandpa-authority = false
babe-threshold = ""

[network]
port = 7001
bootnodes = []
protocol = "/gossamer/ksmcc/0"
nobootstrap = false
nomdns = false

[rpc]
enabled = false
port = 8545
host = "localhost"
modules = ["system"]
ws-port = 8546
ws-enabled = false
