[global]
name = "ksmcc"
id = "ksmcc"
basepath = "~/.gossamer/ksmcc"
log = "info"

[log]
core = ""
network = "trace"
rpc = ""
state = ""
runtime = ""
babe = ""
grandpa = ""

[init]
genesis-raw = "./chain/ksmcc/genesis-raw.json"

[account]
key = ""
unlock = ""

[core]
roles = 1
babe-authority = false
grandpa-authority = false

[network]
port = 7001
bootnodes = []
nobootstrap = false
nomdns = false

[rpc]
enabled = false
external = false
port = 8545
host = "localhost"
modules = ["system", "rpc"]
ws-port = 8546
ws = false
ws-external = false
