// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ChainSafe/gossamer/dot/parachain/availability-distribution (interfaces: SessionCache)
//
// Generated by this command:
//
//	mockgen -destination=mocks_session_cache_test.go -package=availabilitydistribution . SessionCache
//

// Package availabilitydistribution is a generated GoMock package.
package availabilitydistribution

import (
	reflect "reflect"

	parachaintypes "github.com/ChainSafe/gossamer/dot/parachain/types"
	common "github.com/ChainSafe/gossamer/lib/common"
	runtime "github.com/ChainSafe/gossamer/lib/runtime"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionCache is a mock of SessionCache interface.
type MockSessionCache struct {
	ctrl     *gomock.Controller
	recorder *MockSessionCacheMockRecorder
	isgomock struct{}
}

// MockSessionCacheMockRecorder is the mock recorder for MockSessionCache.
type MockSessionCacheMockRecorder struct {
	mock *MockSessionCache
}

// NewMockSessionCache creates a new mock instance.
func NewMockSessionCache(ctrl *gomock.Controller) *MockSessionCache {
	mock := &MockSessionCache{ctrl: ctrl}
	mock.recorder = &MockSessionCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionCache) EXPECT() *MockSessionCacheMockRecorder {
	return m.recorder
}

// GetSessionInfo mocks base method.
func (m *MockSessionCache) GetSessionInfo(sessionIndex parachaintypes.SessionIndex, parent common.Hash, rt runtime.Instance) (*SessionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionInfo", sessionIndex, parent, rt)
	ret0, _ := ret[0].(*SessionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionInfo indicates an expected call of GetSessionInfo.
func (mr *MockSessionCacheMockRecorder) GetSessionInfo(sessionIndex, parent, rt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionInfo", reflect.TypeOf((*MockSessionCache)(nil).GetSessionInfo), sessionIndex, parent, rt)
}

// ReportBadValidators mocks base method.
func (m *MockSessionCache) ReportBadValidators(sessionIndex parachaintypes.SessionIndex, groupIndex parachaintypes.GroupIndex, validators []parachaintypes.AuthorityDiscoveryID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReportBadValidators", sessionIndex, groupIndex, validators)
}

// ReportBadValidators indicates an expected call of ReportBadValidators.
func (mr *MockSessionCacheMockRecorder) ReportBadValidators(sessionIndex, groupIndex, validators any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportBadValidators", reflect.TypeOf((*MockSessionCache)(nil).ReportBadValidators), sessionIndex, groupIndex, validators)
}
