// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ChainSafe/gossamer/lib/keystore (interfaces: Keystore)
//
// Generated by this command:
//
//	mockgen -destination=mocks_keystore_test.go -package=availabilitydistribution github.com/ChainSafe/gossamer/lib/keystore Keystore
//

// Package availabilitydistribution is a generated GoMock package.
package availabilitydistribution

import (
	reflect "reflect"

	common "github.com/ChainSafe/gossamer/lib/common"
	crypto "github.com/ChainSafe/gossamer/lib/crypto"
	keystore "github.com/ChainSafe/gossamer/lib/keystore"
	gomock "go.uber.org/mock/gomock"
)

// MockKeystore is a mock of Keystore interface.
type MockKeystore struct {
	ctrl     *gomock.Controller
	recorder *MockKeystoreMockRecorder
	isgomock struct{}
}

// MockKeystoreMockRecorder is the mock recorder for MockKeystore.
type MockKeystoreMockRecorder struct {
	mock *MockKeystore
}

// NewMockKeystore creates a new mock instance.
func NewMockKeystore(ctrl *gomock.Controller) *MockKeystore {
	mock := &MockKeystore{ctrl: ctrl}
	mock.recorder = &MockKeystoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeystore) EXPECT() *MockKeystoreMockRecorder {
	return m.recorder
}

// GetKeypair mocks base method.
func (m *MockKeystore) GetKeypair(pub crypto.PublicKey) keystore.KeyPair {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeypair", pub)
	ret0, _ := ret[0].(keystore.KeyPair)
	return ret0
}

// GetKeypair indicates an expected call of GetKeypair.
func (mr *MockKeystoreMockRecorder) GetKeypair(pub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeypair", reflect.TypeOf((*MockKeystore)(nil).GetKeypair), pub)
}

// GetKeypairFromAddress mocks base method.
func (m *MockKeystore) GetKeypairFromAddress(pub common.Address) keystore.KeyPair {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeypairFromAddress", pub)
	ret0, _ := ret[0].(keystore.KeyPair)
	return ret0
}

// GetKeypairFromAddress indicates an expected call of GetKeypairFromAddress.
func (mr *MockKeystoreMockRecorder) GetKeypairFromAddress(pub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeypairFromAddress", reflect.TypeOf((*MockKeystore)(nil).GetKeypairFromAddress), pub)
}

// Insert mocks base method.
func (m *MockKeystore) Insert(kp keystore.KeyPair) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", kp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockKeystoreMockRecorder) Insert(kp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockKeystore)(nil).Insert), kp)
}

// Keypairs mocks base method.
func (m *MockKeystore) Keypairs() []keystore.KeyPair {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Keypairs")
	ret0, _ := ret[0].([]keystore.KeyPair)
	return ret0
}

// Keypairs indicates an expected call of Keypairs.
func (mr *MockKeystoreMockRecorder) Keypairs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Keypairs", reflect.TypeOf((*MockKeystore)(nil).Keypairs))
}

// Name mocks base method.
func (m *MockKeystore) Name() keystore.Name {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(keystore.Name)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockKeystoreMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockKeystore)(nil).Name))
}

// PublicKeys mocks base method.
func (m *MockKeystore) PublicKeys() []crypto.PublicKey {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublicKeys")
	ret0, _ := ret[0].([]crypto.PublicKey)
	return ret0
}

// PublicKeys indicates an expected call of PublicKeys.
func (mr *MockKeystoreMockRecorder) PublicKeys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublicKeys", reflect.TypeOf((*MockKeystore)(nil).PublicKeys))
}

// Size mocks base method.
func (m *MockKeystore) Size() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Size")
	ret0, _ := ret[0].(int)
	return ret0
}

// Size indicates an expected call of Size.
func (mr *MockKeystoreMockRecorder) Size() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Size", reflect.TypeOf((*MockKeystore)(nil).Size))
}

// Type mocks base method.
func (m *MockKeystore) Type() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockKeystoreMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockKeystore)(nil).Type))
}
