// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	network "github.com/ChainSafe/gossamer/dot/network"
	mock "github.com/stretchr/testify/mock"
)

// TransactionHandler is an autogenerated mock type for the TransactionHandler type
type TransactionHandler struct {
	mock.Mock
}

// HandleTransactionMessage provides a mock function with given fields: _a0
func (_m *TransactionHandler) HandleTransactionMessage(_a0 *network.TransactionMessage) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*network.TransactionMessage) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
