# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

site_name: Gossamer Docs
site_description: The Official Documentation for Gossamer | A Go Implementation of the Polkadot Host

repo_name: chainsafe/gossamer
repo_url: https://github.com/ChainSafe/gossamer

# Configuration
markdown_extensions:
  - meta
  - admonition
  - codehilite
  - toc:
      permalink: true

theme:
  name: material
  palette:
    primary: pink
    accent: indigo
  favicon: ./assets/favicon.ico

nav:
  - Welcome to Gossamer:
    - Overview: ./index.md
    - Get Started: ./get-started.md
    - General Resources: ./general-resources.md
    - Package Library: ./package-library.md
  - Running Gossamer:
    - Command Line: ./command-line.md
    - Configuration: ./configuration.md
    - Official Nodes: ./official-nodes.md
  - Building Gossamer: 
    - Developer Resources: ./developer-resources.md
    - Host Architecture: ./host-architecture.md
    - Integration Tests: ./integration-tests.md
    - Custom Services: ./custom-services.md
    - Import Runtime: ./import-runtime.md
    - SCALE Examples: ./scale-examples.md
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ChainSafe/gossamer
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ChainSafeth