# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

site_name: Gossamer Docs
site_description: The Official Documentation for Gossamer | A Go Implementation of the Polkadot Host

repo_name: chainsafe/gossamer
repo_url: https://github.com/ChainSafe/gossamer

# Configuration
markdown_extensions:
  - meta
  - admonition
  - codehilite
  - toc:
      permalink: true

theme:
  name: material
  palette:
    primary: pink
    accent: indigo
  favicon: ./assets/favicon.ico
  features:
    # - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
nav:

  - Getting Started:
    - Overview: ./index.md
    - Host Architecture: ./getting-started/overview/host-architecture.md
    - Package Library: ./getting-started/overview/package-library.md
    - Installation: ./getting-started/installation.md
    - General Resources: ./getting-started/resources/general-resources.md
    - Developer Resources: ./getting-started/resources/developer-resources.md
  - Usage:
    - Command Line: ./usage/command-line.md
    - Configuration: ./usage/configuration.md
    - Import Runtime: ./usage/import-runtime.md
    - Import State: ./usage/import-state.md
  - Integrate:
    - Connect to Polkadot.js: ./integrate/connect-to-polkadot-js.md
  - Tests: 
    - Integration Tests: ./testing-and-debugging/integration-tests.md
    - Unit Tests: ./testing-and-debugging/unit-tests.md
    - Docker Tests: ./testing-and-debugging/docker-tests.md
    - Testing: ./testing-and-debugging/unit-test.md
    - Debugging: ./testing-and-debugging/debugging.md
    - Logger usage: ./testing-and-debugging/logger-usage.md
  - Advanced: 
    - SCALE Examples: ./advanced/scale-examples.md
    - Custom Services: ./advanced/custom-services.md
  - Contributing: 
    - Overview: ./contributing.md
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ChainSafe/gossamer
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ChainSafeth