services: 
  alice:
    platform: linux/amd64
    build:
      context: ./../..
      dockerfile: devnet/alice.Dockerfile
      args:
        CHAIN: cross-client
        DD_API_KEY: ${DD_API_KEY}
    ports:
      - 7001
      - 8545
      - 8546
      - 8540
      - 9876
      - 6060

  bob:
    platform: linux/amd64
    build:
      context: ./../..
      dockerfile: devnet/bob.Dockerfile
      args:
        key: bob
        CHAIN: cross-client
        DD_API_KEY: ${DD_API_KEY}
    ports:
      - 7001
      - 8545
      - 8546
      - 9876
    depends_on:
      - alice

  charlie:
    platform: linux/amd64
    build:
      context: ./../..
      dockerfile: devnet/substrate_bob.Dockerfile
      args:
        key: charlie
        CHAIN: cross-client
        DD_API_KEY: ${DD_API_KEY}
    ports:
      - 7001
      - 8545
      - 8546
      - 9876
    depends_on:
      - alice