services: 
  alice:
    platform: linux/amd64
    build:
      context: ./../..
      dockerfile: devnet/alice.Dockerfile
      args:
        DD_API_KEY: ${DD_API_KEY}
    # we map ports on the host to random available ports such that one Gossamer instance do not conflict 
    # with another instance, and we can use local tooling to interact with Gossamer through this port mapping. 
    # You can find the port mapping with docker ps
    ports:
      - 7001
      - 8545
      - 8546
      - 8540
      - 9876
      - 6060

  bob:
    platform: linux/amd64
    build:
      context: ./../..
      dockerfile: devnet/bob.Dockerfile
      args:
        key: bob
        DD_API_KEY: ${DD_API_KEY}
    ports:
      - 7001
      - 8545
      - 8546
      - 8540
      - 9876
      - 6060
    depends_on:
      - alice

  charlie:
    platform: linux/amd64
    build:
      context: ./../..
      dockerfile: devnet/substrate_bob.Dockerfile
      args:
        key: charlie
        DD_API_KEY: ${DD_API_KEY}
    ports:
      - 7001
      - 8545
      - 8546
      - 9876
    depends_on:
      - alice
