// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	wasmtime "github.com/bytecodealliance/wasmtime-go"
)

// ImportsFunc is an autogenerated mock type for the ImportsFunc type
type ImportsFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *ImportsFunc) Execute(_a0 *wasmtime.Store, _a1 *wasmtime.Memory) (*wasmtime.Linker, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *wasmtime.Linker
	if rf, ok := ret.Get(0).(func(*wasmtime.Store, *wasmtime.Memory) *wasmtime.Linker); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wasmtime.Linker)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*wasmtime.Store, *wasmtime.Memory) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
