[global]
data-dir = "~/.gossamer"
authority = true

[network]
bootstrap-nodes = []
port = 7001
no-bootstrap = false
no-mdns = false

[rpc]
port = 8545
host = "localhost"
modules = ["system", "author"]
