[global]
name = "gssmr"
id = "gssmr"
config = "./node/gssmr/config.toml"
genesis = "./node/gssmr/genesis.json"
datadir = "~/.gossamer/gssmr"
roles = 4

[account]
key = ""
unlock = ""

[core]
authority = true

[network]
port = 7001
bootnodes = []
protocol = "/gossamer/gssmr/0"
nobootstrap = false
nomdns = false

[rpc]
enabled = false
port = 8545
host = "localhost"
modules = ["system", "author", "chain"]
