[global]
name = "gssmr"
id = "gssmr"
datadir = "~/.gossamer/gssmr"

[account]
key = ""
unlock = ""

[core]
authority = true
roles = 4

[network]
port = 7001
bootnodes = []
protocol = "/gossamer/gssmr/0"
nobootstrap = false
nomdns = false

[rpc]
enabled = false
port = 8545
host = "localhost"
modules = ["system", "author", "chain"]

[init]
genesis = "./node/gssmr/genesis.json"
