// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ChainSafe/gossamer/dot/digest (interfaces: EpochState)
//
// Generated by this command:
//
//	mockgen -destination=mock_epoch_state_test.go -package digest . EpochState
//

// Package digest is a generated GoMock package.
package digest

import (
	reflect "reflect"

	types "github.com/ChainSafe/gossamer/dot/types"
	gomock "go.uber.org/mock/gomock"
)

// MockEpochState is a mock of EpochState interface.
type MockEpochState struct {
	ctrl     *gomock.Controller
	recorder *MockEpochStateMockRecorder
	isgomock struct{}
}

// MockEpochStateMockRecorder is the mock recorder for MockEpochState.
type MockEpochStateMockRecorder struct {
	mock *MockEpochState
}

// NewMockEpochState creates a new mock instance.
func NewMockEpochState(ctrl *gomock.Controller) *MockEpochState {
	mock := &MockEpochState{ctrl: ctrl}
	mock.recorder = &MockEpochStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEpochState) EXPECT() *MockEpochStateMockRecorder {
	return m.recorder
}

// FinalizeBABENextConfigData mocks base method.
func (m *MockEpochState) FinalizeBABENextConfigData(finalizedHeader *types.Header) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalizeBABENextConfigData", finalizedHeader)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinalizeBABENextConfigData indicates an expected call of FinalizeBABENextConfigData.
func (mr *MockEpochStateMockRecorder) FinalizeBABENextConfigData(finalizedHeader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizeBABENextConfigData", reflect.TypeOf((*MockEpochState)(nil).FinalizeBABENextConfigData), finalizedHeader)
}

// FinalizeBABENextEpochData mocks base method.
func (m *MockEpochState) FinalizeBABENextEpochData(finalizedHeader *types.Header) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalizeBABENextEpochData", finalizedHeader)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinalizeBABENextEpochData indicates an expected call of FinalizeBABENextEpochData.
func (mr *MockEpochStateMockRecorder) FinalizeBABENextEpochData(finalizedHeader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizeBABENextEpochData", reflect.TypeOf((*MockEpochState)(nil).FinalizeBABENextEpochData), finalizedHeader)
}

// GetEpochForBlock mocks base method.
func (m *MockEpochState) GetEpochForBlock(header *types.Header) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpochForBlock", header)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEpochForBlock indicates an expected call of GetEpochForBlock.
func (mr *MockEpochStateMockRecorder) GetEpochForBlock(header any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpochForBlock", reflect.TypeOf((*MockEpochState)(nil).GetEpochForBlock), header)
}

// HandleBABEDigest mocks base method.
func (m *MockEpochState) HandleBABEDigest(header *types.Header, digest types.BabeConsensusDigest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleBABEDigest", header, digest)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleBABEDigest indicates an expected call of HandleBABEDigest.
func (mr *MockEpochStateMockRecorder) HandleBABEDigest(header, digest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleBABEDigest", reflect.TypeOf((*MockEpochState)(nil).HandleBABEDigest), header, digest)
}
