on: [pull_request]
name: checks
env:
  GO111MODULE: on

jobs:
  linter-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.15.x'
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          args: --config .golangci.yml

  vet-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.15.x'
      - uses: actions/checkout@v2

#      Turn back on when #1243 lands
#      - name: Run go vet
#        run: go vet ./...