name: checks (skip)
on:
  pull_request:
    paths-ignore:
      - .github/workflows/checks.yml
      - .github/PULL_REQUEST/pull_request.go
      - .golangci.yml
      - "**/*.go"
      - go.mod
      - go.sum

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Skipping workflow. See why this workflow exists:"
          echo "https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks"
