on:
  pull_request:
    # Commented paths to avoid skipping required workflow
    # See https://github.community/t/feature-request-conditional-required-checks/16761
    # paths:
    #   - .github/workflows/checks.yml
    #   - .github/PULL_REQUEST/pull_request.go
    #   - .golangci.yml
    #   - "**/*.go"
    #   - go.mod
    #   - go.sum

name: checks

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          stable: true
          check-latest: true

      - name: Lint
        run: make lint
