name: checks
on:
  pull_request:
    paths:
      - .github/workflows/checks.yml
      - .github/PULL_REQUEST/pull_request.go
      - .golangci.yml
      - "**/*.go"
      - go.mod
      - go.sum

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          stable: true
          check-latest: true

      - name: Lint
        run: make lint
