on: [pull_request]
name: checks
env:
  GO111MODULE: on

jobs:
  linter-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run go fmt
        run: diff -u <(echo -n) <(gofmt -d -s .)

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:          
          version: 'latest'

  vet-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.x'
      - uses: actions/checkout@v2

      - name: Run go vet
        run: go vet ./...