on:
  pull_request:
    # Commented paths to avoid skipping required workflow
    # See https://github.community/t/feature-request-conditional-required-checks/16761
    # paths:
    #   - .github/workflows/checks.yml
    #   - .github/PULL_REQUEST/pull_request.go
    #   - .golangci.yml
    #   - "**/*.go"
    #   - go.mod
    #   - go.sum

name: checks

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          stable: true
          check-latest: true

      - name: Snake case test cases
        run: |
          go run ./cmd/testcases/main.go && \
          git diff --exit-code

      - name: Lint
        run: make lint

      - name: Up to date Go proto generated
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28 && \
          PROTOC_VERSION=21.10 && \
          curl -sL --output protoc.zip "https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip" && \
          sudo unzip protoc.zip -d /usr/local && \
          rm protoc.zip && \
          go generate -run "protoc" ./... && \
          git diff --exit-code
