on: [pull_request]
name: checks
env:
  GO111MODULE: on

jobs:
  linter-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run go fmt
        run: diff -u <(echo -n) <(gofmt -d -s .)

      - name: golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.41.0
          $(go env GOPATH)/bin/golangci-lint run

  vet-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.x'
      - uses: actions/checkout@v2

      - name: Run go vet
        run: go vet ./...