name: Copyright check
on:
  pull_request:
    branches:
      - development
    # Commented paths to avoid skipping required workflow
    # See https://github.community/t/feature-request-conditional-required-checks/16761
    # paths:
    #   - .github/workflows/copyright.yml
    #   - "**/*.go"
    #   - "**/*.proto"

jobs:
  copyright-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
          stable: true
          check-latest: true

      - run: make license

      - run: git diff --exit-code
