on:
  pull_request:
    # Commented paths to avoid skipping required workflow
    # See https://github.community/t/feature-request-conditional-required-checks/16761
    # paths:
    #   - .github/workflows/docker-stress.yml
    #   - "**/*.go"
    #   - "chain/**"
    #   - "cmd/**"
    #   - "dot/**"
    #   - "internal/**"
    #   - "lib/**"
    #   - "pkg/**"
    #   - "tests/stress/**"
    #   - go.mod
    #   - go.sum
name: docker-stress
env:
  GO111MODULE: on

jobs:
  docker-stress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          load: true
          file: ./Dockerfile
          target: builder
          platforms: linux/amd64
          push: false
          tags: chainsafe/gossamer:test

      - name: Run stress
        run: |
          docker run chainsafe/gossamer:test sh -c "make it-stress"
