name: docker-stress
on:
  pull_request:
    paths:
      - .github/workflows/docker-stress.yml
      - "**/*.go"
      - "chain/**"
      - "cmd/gossamer/**"
      - "dot/**"
      - "internal/**"
      - "lib/**"
      - "pkg/**"
      - "tests/stress/**"
      - go.mod
      - go.sum

jobs:
  docker-stress-tests:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - uses: docker/build-push-action@v3
        with:
          load: true
          target: builder
          tags: chainsafe/gossamer:test

      - name: Run stress
        run: |
          docker run chainsafe/gossamer:test sh -c "make it-stress"
