on:
  pull_request:
    # Commented paths to avoid skipping required workflow
    # See https://github.community/t/feature-request-conditional-required-checks/16761
    # paths:
    #   - .github/workflows/integration-tests.yml
    #   - "**/*.go"
    #   - "chain/**"
    #   - "cmd/**"
    #   - "dot/**"
    #   - "internal/**"
    #   - "lib/**"
    #   - "pkg/**"
    #   - "tests/**"
    #   - go.mod
    #   - go.sum
name: integration-tests

jobs:
  integration-tests:
    timeout-minutes: 60
    strategy:
      matrix:
        packages:
          [
            github.com/ChainSafe/gossamer/dot,
            github.com/ChainSafe/gossamer/dot/core,
            github.com/ChainSafe/gossamer/dot/rpc,
            github.com/ChainSafe/gossamer/dot/rpc/modules,
            github.com/ChainSafe/gossamer/dot/rpc/subscription,
            github.com/ChainSafe/gossamer/dot/state,
            github.com/ChainSafe/gossamer/dot/digest,
            github.com/ChainSafe/gossamer/dot/network,
            github.com/ChainSafe/gossamer/dot/sync,
            github.com/ChainSafe/gossamer/lib/babe,
            github.com/ChainSafe/gossamer/lib/grandpa,
          ]
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true

      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          stable: true
          check-latest: true

      - name: Set cache variables
        id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      - uses: actions/checkout@v4

      - name: Go build cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-build

      - name: Go modules cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-mod

      - name: Run integration tests
        run: go test -timeout=45m -tags integration ${{ matrix.packages }}
