name: Mocks check
on:
  pull_request:
    branches:
      - development
    paths:
      - .github/workflows/mocks.yml
      - "**/*.go"

jobs:
  mocks-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          stable: true
          check-latest: true

      - run: go install github.com/vektra/mockery/v2@v2.14

      - run: go install github.com/golang/mock/mockgen@v1.6

      - name: Check devnet module
        run: |
          cd devnet && \
          go mod download && \
          go generate -run "mockery" -tags integration ./... && \
          go generate -run "mockgen" -tags integration ./... && \
          git diff --exit-code && \
          cd ..

      - name: Check Gossamer module
        run: |
          go mod download && \
          go generate -run "mockery" -tags integration ./... && \
          go generate -run "mockgen" -tags integration ./... && \
          git diff --exit-code
