name: skip-packages-check
on:
  pull_request:
    paths:
      - .github/workflows/integration-tests.yml
      - .github/workflows/integration-tests-skip.yml
      - "cmd/skipcheck/**"

jobs:
  integration-tests-skip-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          stable: true
          check-latest: true

      - run: go run cmd/skipcheck/main.go
