name: staging
on:
  push:
    branches:
      - tim-staging

env:
  GO111MODULE: on

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ls -a
        run: ls -a
      
      - name: pwd
        run: pwd

      - name: build docker image
        run: docker build -f=Dockerfile.staging . --progress=plain -t=gossamer-polkadot:latest --build-arg chain=polkadot