on:
  pull_request:
    # Commented paths to avoid skipping required workflow
    # See https://github.community/t/feature-request-conditional-required-checks/16761
    # paths:
    #   - .github/workflows/unit-tests.yml
    #   - "**/*.go"
    #   - "chain/**"
    #   - "cmd/**"
    #   - "dot/**"
    #   - "internal/**"
    #   - "lib/**"
    #   - "pkg/**"
    #   - "tests/**"
    #   - go.mod
    #   - go.sum
    #   - Makefile
name: unit-tests

jobs:
  state-race:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          stable: true
          check-latest: true

      - name: Set cache variables
        id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      - uses: actions/checkout@v3

      - name: Go build cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-build

      - name: Go modules cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-mod

      - run: make test-state-race

  unit-tests:
    timeout-minutes: 60
    strategy:
      matrix:
        packages:
          [
            github.com/ChainSafe/gossamer/cmd/gossamer,
            github.com/ChainSafe/gossamer/dot,
            github.com/ChainSafe/gossamer/dot/config/...,
            github.com/ChainSafe/gossamer/dot/core/...,
            github.com/ChainSafe/gossamer/dot/digest/...,
            github.com/ChainSafe/gossamer/dot/network/...,
            github.com/ChainSafe/gossamer/dot/peerset/...,
            github.com/ChainSafe/gossamer/dot/rpc/...,
            github.com/ChainSafe/gossamer/dot/state/...,
            github.com/ChainSafe/gossamer/dot/sync/...,
            github.com/ChainSafe/gossamer/dot/system/...,
            github.com/ChainSafe/gossamer/dot/telemetry/...,
            github.com/ChainSafe/gossamer/dot/types/...,
            github.com/ChainSafe/gossamer/internal/...,
            github.com/ChainSafe/gossamer/lib/babe/...,
            github.com/ChainSafe/gossamer/lib/blocktree/...,
            github.com/ChainSafe/gossamer/lib/common/...,
            github.com/ChainSafe/gossamer/lib/crypto/...,
            github.com/ChainSafe/gossamer/lib/genesis/...,
            github.com/ChainSafe/gossamer/lib/grandpa/...,
            github.com/ChainSafe/gossamer/lib/keystore/...,
            github.com/ChainSafe/gossamer/lib/runtime/...,
            github.com/ChainSafe/gossamer/lib/services/...,
            github.com/ChainSafe/gossamer/lib/transaction/...,
            github.com/ChainSafe/gossamer/lib/trie/...,
            github.com/ChainSafe/gossamer/lib/utils/...,
            github.com/ChainSafe/gossamer/pkg/...,
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          stable: true
          check-latest: true

      - name: Set cache variables
        id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      - uses: actions/checkout@v3

      - name: Go build cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-build

      - name: Go modules cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-mod

      - name: Install Subkey
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            wget -P $HOME/.local/bin/ https://chainbridge.ams3.digitaloceanspaces.com/subkey-v2.0.0
            mv $HOME/.local/bin/subkey-v2.0.0 $HOME/.local/bin/subkey
          elif [ "$RUNNER_OS" == "macOS" ]; then
            wget -P $HOME/.local/bin/ https://chainbridge.ams3.digitaloceanspaces.com/subkey-v2.0.0-macos
            mv $HOME/.local/bin/subkey-v2.0.0-macos $HOME/.local/bin/subkey
          else
            echo "Subkey for $RUNNER_OS is not supported"
            exit 1
          fi

          chmod +x $HOME/.local/bin/subkey
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run unit tests
        run: go test -short -coverprofile=coverage.out -covermode=atomic -timeout=30m ${{ matrix.packages }}

      - uses: codecov/codecov-action@v3.1.0
        with:
          if_ci_failed: success
          informational: true
          files: ./coverage.out
          flags: unit-tests
          name: coverage
          verbose: true
