name: unit-tests
on:
  pull_request:
    paths-ignore:
      - .github/workflows/unit-tests.yml
      - "**/*.go"
      - "chain/**"
      - "cmd/gossamer/**"
      - "dot/**"
      - "internal/**"
      - "lib/**"
      - "pkg/**"
      - "tests/**"
      - go.mod
      - go.sum
      - Makefile

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Skipping workflow. See why this workflow exists:"
          echo "https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks"
