name: zombienet
run-name: ${{ github.actor }} is running Zombienet tests
on: [push]
jobs:
  zombienet-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build gossamer
        run: make build

      - name: Install Zombienet
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            wget -P $HOME/.local/bin/ https://github.com/paritytech/zombienet/releases/download/v1.3.41/zombienet-linux-x64
            mv $HOME/.local/bin/zombienet-linux-x64 $HOME/.local/bin/zombienet
          elif [ "$RUNNER_OS" == "macOS" ]; then
            wget -P $HOME/.local/bin/ https://github.com/paritytech/zombienet/releases/download/v1.3.41/zombienet-macos
            mv $HOME/.local/bin/zombienet-macos $HOME/.local/bin/zombienet
          else
            echo "Zombienet for $RUNNER_OS is not supported"
            exit 1
          fi

          chmod +x $HOME/.local/bin/zombienet
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Zombienet Version
        run: |
          zombienet version

      - name: Zombienet test
        run: |
          zombienet test -p native zombienet_tests/functional/0001-basic-network.zndsl
