name: zombienet
run-name: ${{ github.actor }} is running Zombienet tests
on: [push]
jobs:
  zombienet-tests:
    runs-on: ubuntu-latest
    steps:
      - run: npm install -g bats
      - run: bats -v
