name: zombienet
run-name: ${{ github.actor }} is running Zombienet tests
on: [push]
jobs:
  zombienet-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Bats
        run: npm install -g bats

      - name: Run Bats
        run: bats -v
