name: zombienet
run-name: ${{ github.actor }} is running Zombienet tests
on: [push]
jobs:
  zombienet-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          stable: true
          check-latest: true

      - name: Set cache variables
        id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      - uses: actions/checkout@v3

      - name: Go build cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-build

      - name: Go modules cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-mod

      - name: Run build
        run: make build

      - name: Gossamer version
        run: |
          ./bin/gossamer --version
          echo ${{ steps.go-cache-paths.outputs.go-build }}
          cd ${{ steps.go-cache-paths.outputs.go-build }}
          ls -al
          mv ./bin/gossamer $HOME/.local/bin/gossamer
          gossamer --version

      - name: Install Zombienet
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            wget -P $HOME/.local/bin/ https://github.com/paritytech/zombienet/releases/download/v1.3.41/zombienet-linux-x64
            mv $HOME/.local/bin/zombienet-linux-x64 $HOME/.local/bin/zombienet
          elif [ "$RUNNER_OS" == "macOS" ]; then
            wget -P $HOME/.local/bin/ https://github.com/paritytech/zombienet/releases/download/v1.3.41/zombienet-macos
            mv $HOME/.local/bin/zombienet-macos $HOME/.local/bin/zombienet
          else
            echo "Zombienet for $RUNNER_OS is not supported"
            exit 1
          fi

          chmod +x $HOME/.local/bin/zombienet
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Zombienet Version
        run: |
          zombienet version

      - name: Zombienet test
        run: |
          zombienet test -p native zombienet_tests/functional/0001-basic-network.zndsl
