name: zombienet
run-name: ${{ github.actor }} is running Zombienet tests
on: [push]
jobs:
  zombienet-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Subkey
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            wget -P $HOME/.local/bin/ https://chainbridge.ams3.digitaloceanspaces.com/subkey-v2.0.0
            mv $HOME/.local/bin/subkey-v2.0.0 $HOME/.local/bin/subkey
          elif [ "$RUNNER_OS" == "macOS" ]; then
            wget -P $HOME/.local/bin/ https://chainbridge.ams3.digitaloceanspaces.com/subkey-v2.0.0-macos
            mv $HOME/.local/bin/subkey-v2.0.0-macos $HOME/.local/bin/subkey
          else
            echo "Subkey for $RUNNER_OS is not supported"
            exit 1
          fi

          chmod +x $HOME/.local/bin/subkey
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Bats
        run: npm install -g bats

      - name: Run Bats
        run: bats -v
