services: 
  alice:
    platform: linux/amd64
    build:
      context: ./..
      dockerfile: devnet/alice.Dockerfile
      args:
        DD_API_KEY: ${DD_API_KEY}
    ports:
      - 7001
      - 8545
      - 8546
      - 8540
      - 9876
      - 6060

  bob:
    platform: linux/amd64
    build:
      context: ./..
      dockerfile: devnet/bob.Dockerfile
      args:
        DD_API_KEY: ${DD_API_KEY}
        key: bob
    ports:
      - 7001
      - 8545
      - 8546
      - 8540
      - 9876
      - 6060
    depends_on:
      - alice

  charlie:
    platform: linux/amd64
    build:
      context: ./..
      dockerfile: devnet/bob.Dockerfile
      args:
        DD_API_KEY: ${DD_API_KEY}
        key: charlie
    ports:
      - 7001
      - 8545
      - 8546
      - 8540
      - 9876
    depends_on:
      - alice

  substrate-alice:
    platform: linux/amd64
    build:
      context: ./..
      dockerfile: devnet/substrate_alice.Dockerfile
    ports:
      - 30333
      - 9933
      - 9944
      - 9615

  substrate-bob:
    platform: linux/amd64
    build:
      context: ./..
      dockerfile: devnet/substrate_bob.Dockerfile
      args:
        key: bob
    ports:
      - 30333
      - 9933
      - 9944
      - 9615
    depends_on:
      - substrate-alice

  substrate-charlie:
    platform: linux/amd64
    build:
      context: ./..
      dockerfile: devnet/substrate_bob.Dockerfile
      args:
        key: charlie
    ports:
      - 30333
      - 9933
      - 9944
      - 9615
    depends_on:
      - substrate-alice