services: 
  alice:
    build:
      context: ./..
      dockerfile: devnet/alice.Dockerfile
      args:
        DD_API_KEY: ${DD_API_KEY}
    healthcheck:
      test: >
        curl --request POST 'http://localhost:8545' --header 'Content-Type: application/json' --data-raw '{"jsonrpc":"2.0","method":"system_name","params":[],"id":1}' || exit 1
      interval: 30s
      timeout: 15s
      retries: 5
    ports:
      - 7001
      - 8545
      - 8546
      - 8540
      - 9876

  bob:
    build:
      context: ./..
      dockerfile: devnet/bob.Dockerfile
      args:
        DD_API_KEY: ${DD_API_KEY}
        key: bob
        port: 7002
    healthcheck:
      test: >
        curl --request POST 'http://localhost:8545' --header 'Content-Type: application/json' --data-raw '{"jsonrpc":"2.0","method":"system_name","params":[],"id":1}' || exit 1
      interval: 30s
      timeout: 15s
      retries: 5
    ports:
      - 7002
      - 8545
      - 8546
      - 8540
      - 9876
    depends_on:
      - alice

  charlie:
    build:
      context: ./..
      dockerfile: devnet/bob.Dockerfile
      args:
        DD_API_KEY: ${DD_API_KEY}
        key: charlie
        port: 7003
    healthcheck:
      test: >
        curl --request POST 'http://localhost:8545' --header 'Content-Type: application/json' --data-raw '{"jsonrpc":"2.0","method":"system_name","params":[],"id":1}' || exit 1
      interval: 30s
      timeout: 15s
      retries: 5
    ports:
      - 7003
      - 8545
      - 8546
      - 8540
      - 9876
    depends_on:
      - alice