services: 
  alice:
    build:
      context: ./..
      dockerfile: devnet/alice.Dockerfile
      args:
        DD_API_KEY: ${DD_API_KEY}
    ports:
      - 7001
      - 8545
      - 8546
      - 8540
      - 9876

  bob:
    build:
      context: ./..
      dockerfile: devnet/bob.Dockerfile
      args:
        DD_API_KEY: ${DD_API_KEY}
        key: bob
    ports:
      - 7001
      - 8545
      - 8546
      - 8540
      - 9876
    depends_on:
      - alice

  charlie:
    build:
      context: ./..
      dockerfile: devnet/bob.Dockerfile
      args:
        DD_API_KEY: ${DD_API_KEY}
        key: charlie
    ports:
      - 7001
      - 8545
      - 8546
      - 8540
      - 9876
    depends_on:
      - alice

