services: 
  alice:
    build:
      context: ./..
      dockerfile: devnet/alice.Dockerfile
      args:
        DD_API_KEY: ${DD_API_KEY}
        pubip: 10.5.0.2
    ports:
      - 7001
      - 8545
      - 8546
      - 8540
      - 9876
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  bob:
    build:
      context: ./..
      dockerfile: devnet/bob.Dockerfile
      args:
        DD_API_KEY: ${DD_API_KEY}
        key: bob
        pubip: 10.5.0.3
    ports:
      - 7001
      - 8545
      - 8546
      - 8540
      - 9876
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    depends_on:
      - alice

  charlie:
    build:
      context: ./..
      dockerfile: devnet/bob.Dockerfile
      args:
        DD_API_KEY: ${DD_API_KEY}
        key: charlie
        pubip: 10.5.0.4
    ports:
      - 7001
      - 8545
      - 8546
      - 8540
      - 9876
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    depends_on:
      - alice

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1