services: 
  alice:
    platform: linux/amd64
    build:
      context: ./..
      dockerfile: devnet/alice.Dockerfile
      args:
        DD_API_KEY: ${DD_API_KEY}
    ports:
      - 7001
      - 8545
      - 8546
      - 8540
      - 9876

  bob:
    platform: linux/amd64
    build:
      context: ./..
      dockerfile: devnet/bob.Dockerfile
      args:
        DD_API_KEY: ${DD_API_KEY}
        key: bob
    ports:
      - 7001
      - 8545
      - 8546
      - 8540
      - 9876
    depends_on:
      - alice

  charlie:
    platform: linux/amd64
    build:
      context: ./..
      dockerfile: devnet/bob.Dockerfile
      args:
        DD_API_KEY: ${DD_API_KEY}
        key: charlie
    ports:
      - 7001
      - 8545
      - 8546
      - 8540
      - 9876
    depends_on:
      - alice
  
  substrate:
    platform: linux/amd64
    build:
      context: ./..
      dockerfile: devnet/substrate.Dockerfile
    ports:
      - 30333
      - 9933
      - 9944
      - 9615
    depends_on:
      - alice