services: 
  alice:
    platform: linux/amd64
    build:
      context: ./..
      dockerfile: devnet/alice.Dockerfile
      args:
        DD_API_KEY: ${DD_API_KEY}
    ports:
      - 7001
      - 8545
      - 8546
      - 8540
      - 9876
      - 6060

  bob:
    platform: linux/amd64
    build:
      context: ./..
      dockerfile: devnet/substrate_bob.Dockerfile
      args:
        DD_API_KEY: ${DD_API_KEY}
        key: bob
    ports:
      - 7001
      - 8545
      - 8546
      - 8540
      - 9876
      - 6060

  charlie:
    platform: linux/amd64
    build:
      context: ./..
      dockerfile: devnet/substrate_bob.Dockerfile
      args:
        DD_API_KEY: ${DD_API_KEY}
        key: charlie
    ports:
      - 7001
      - 8545
      - 8546
      - 8540
      - 9876
